[Bugfix] fix refresh not failed after modify table column type
StarRocks/starrocks pull request #10145
Opened 2022-08-18 03:48 UTC by QingdongZeng3

[Bugfix] fix refresh not failed after modify table column type

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9895

## Problem Summary(Required) ：

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

2022-08-18 04:11 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 23 (26.09%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|6|23|26.09%|[573, 574, 575, 576, 577, 579, 580, 581, 588, 589, 590, 591, 592, 593, 595, 596, 597]|

2022-08-18 04:58 UTC, QingdongZeng3 commented
@Astralidea PTAL

2022-08-19 06:19 UTC, QingdongZeng3 commented
run starrocks_admit_test

2022-08-19 09:23 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java
> +                    MaterializedView mv = (MaterializedView) db.getTable(mvId);
should check mv is null

2022-08-19 10:50 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 26 (23.08%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|6|26|23.08%|[573, 574, 575, 576, 577, 579, 580, 581, 588, 589, 590, 591, 592, 593, 595, 596, 597, 599, 600, 601]|

2022-08-19 11:23 UTC, Astralidea approved these changes, later dismissed

2022-08-20 02:06 UTC, ABingHuang requested changes
could you add an UT for it?

2022-08-22 05:36 UTC, QingdongZeng3 commented
run starrocks_admit_test

2022-08-22 05:36 UTC, QingdongZeng3 commented
> could you add an UT for it?

ok

2022-08-22 05:41 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 24 / 26 (92.31%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|24|26|92.31%|[592, 593]|

2022-08-22 06:45 UTC, ABingHuang approved these changes
LGTM

2022-08-22 06:45 UTC, Astralidea approved these changes

2022-08-22 06:46 UTC, wanpengfei-git commented
run starrocks_admit_test

2022-08-22 06:46 UTC, gengjun-git approved these changes

2022-08-22 08:04 UTC, merged

2022-08-22 09:07 UTC, Astralidea commented
@Mergifyio backport branch-2.4