first ver
StarRocks/starrocks pull request #10301
Opened 2022-08-22 07:34 UTC by abc982627271

## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

2022-08-23 16:09 UTC, chaoyli requested changes, later dismissed

2022-08-23 16:09 UTC, chaoyli commented on fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadJob.java
> +                                PushBrokerReaderParams params = getPushBrokerReaderParams(table, indexId);
What's the purpose of the pr? Feature/BugFix/Enhancement or Refactor. You have to describe it in the commit message.

2022-08-25 13:00 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 41 / 78 (52.56%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|0|18|00.00%|[466, 498, 499, 534, 535, 536, 537, 539, 540, 542, 544, 545, 546, 548, 549, 550, 551, 553]|
|:large_blue_circle:|com/starrocks/lake/LakeTablet.java|0|1|00.00%|[86]|
|:large_blue_circle:|com/starrocks/task/PushTask.java|1|2|50.00%|[183]|
|:large_blue_circle:|com/starrocks/load/loadv2/SparkLoadJob.java|40|57|70.18%|[502, 503, 504, 505, 506, 509, 510, 511, 512, 513, 514, 516, 517, 518, 603, 604, 605]|

2022-08-25 13:18 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 41 / 78 (52.56%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|0|18|00.00%|[466, 498, 499, 534, 535, 536, 537, 539, 540, 542, 544, 545, 546, 548, 549, 550, 551, 553]|
|:large_blue_circle:|com/starrocks/lake/LakeTablet.java|0|1|00.00%|[86]|
|:large_blue_circle:|com/starrocks/task/PushTask.java|1|2|50.00%|[183]|
|:large_blue_circle:|com/starrocks/load/loadv2/SparkLoadJob.java|40|57|70.18%|[502, 503, 504, 505, 506, 509, 510, 511, 512, 513, 514, 516, 517, 518, 603, 604, 605]|

2022-08-26 02:22 UTC, sduzh commented on be/src/storage/lake/spark_load.cpp
> +    return Status::OK();
if (push_type == PUSH_NORMAL_V2) {
    return _load_convert(tablet, request);
} else {
    return Status::NotSupported(fmt::format("unsupported push type for lake table: {}", push_type));
}

2022-08-26 02:24 UTC, sduzh commented on be/src/storage/lake/spark_load.cpp
> +    load_id.set_lo(0);
unused variables

2022-08-26 02:25 UTC, sduzh commented on be/src/storage/lake/spark_load.cpp
> +             << num_rows;
```suggestion
    VLOG(10) << "convert delta file end. res=" << st.to_string() << ", tablet=" << cur_tablet.id() << ", processed_rows="
             << writer->num_rows();
```

2022-08-26 02:28 UTC, sduzh commented on be/src/storage/lake/spark_load.cpp
> +            }
```suggestion
            if (!st.ok()) {
                LOG(WARNING) << "Fail to read broker: " << st;
                return st;
            } else if (reader->eof()) {
                break;
            } else {
                ChunkHelper::padding_char_columns(char_field_indexes, schema, *tablet_schema, chunk.get());
                RETURN_IF_ERROR(writer->write(*chunk));
                chunk->reset();
            }
```

2022-08-26 02:29 UTC, sduzh commented on be/src/storage/task/engine_batch_load_task.cpp
> +}
useless function

2022-08-26 02:31 UTC, sduzh commented on be/src/storage/task/engine_batch_load_task.cpp
> +            LOG(WARNING) << "Fail to load file. res=" << res << ", txn_id: " << request.transaction_id
```suggestion
            LOG(WARNING) << "Fail to load file. res=" << res << ", txn_id=" << request.transaction_id
```

2022-08-26 02:32 UTC, sduzh commented on be/src/storage/task/engine_batch_load_task.cpp
> +                      << ". txn_id: " << request.transaction_id << ", tablet=" << tablet.id()
```suggestion
                      << ". txn_id=" << request.transaction_id << ", tablet=" << tablet.id()
```

2022-08-26 02:32 UTC, sduzh commented on be/src/storage/task/engine_batch_load_task.cpp
> +            LOG(WARNING) << "Fail to load file. res=" << res << ", txn_id: " << request.transaction_id
```suggestion
            LOG(WARNING) << "Fail to load file. res=" << res << ", txn_id=" << request.transaction_id
```

2022-08-26 02:32 UTC, sduzh commented on be/src/storage/task/engine_batch_load_task.cpp
> +                      << ". txn_id: " << request.transaction_id << ", tablet=" << tablet->full_name()
```suggestion
                      << ". txn_id=" << request.transaction_id << ", tablet=" << tablet->full_name()
```

2022-08-26 02:33 UTC, sduzh commented on fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
> +                    LOG.info("replica: {}", replica);
Remove this log.

2022-08-26 02:35 UTC, sduzh commented on fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
> +            return allQueryableReplicas.get(0);
```suggestion
            return allQueryableReplicas.isEmpty() ? null : allQueryableReplicas.get(0);
```

2022-08-26 02:36 UTC, sduzh commented on fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
> +            }
```suggestion
            if (allQueryableReplicas.isEmpty()) {
                LOG.warn("no queryable replica found in tablet {}", tabletId);
                return null;
            }
```

2022-08-26 02:36 UTC, sduzh commented on fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadJob.java
> +                                    LOG.info("tablet is LocalTablet");
Remove this log.

2022-08-26 02:37 UTC, tracymacding commented on fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
> +                    LOG.info("replica: {}", replica);
remove it

2022-08-26 02:37 UTC, tracymacding commented on fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
> +                LOG.warn("no queryable replica found in tablet {}", tabletId);
should return null

2022-08-26 02:38 UTC, sduzh commented on be/src/storage/lake/spark_load.cpp
> +                  << ", txn_id: " << request.transaction_id;
```suggestion
                  << ", txn_id=" << request.transaction_id;
```

2022-08-26 02:38 UTC, sduzh commented on be/src/storage/lake/spark_load.cpp
> +    LOG(INFO) << "begin to realtime vectorized push. tablet=" << tablet.id() << ", txn_id: " << request.transaction_id;
```suggestion
    LOG(INFO) << "begin to realtime vectorized push. tablet=" << tablet.id() << ", txn_id=" << request.transaction_id;
```

2022-08-26 02:39 UTC, sduzh commented on be/src/storage/lake/spark_load.cpp
> +    return Status::OK();
```suggestion
```
if (push_type == PUSH_NORMAL_V2) {
    return _load_convert(tablet, request);
} else {
    return Status::NotSupported(fmt::format("unsupported push type for lake table: {}", push_type));
}
```
```

2022-08-26 02:57 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 41 / 78 (52.56%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|0|18|00.00%|[466, 498, 499, 534, 535, 536, 537, 539, 540, 542, 544, 545, 546, 548, 549, 550, 551, 553]|
|:large_blue_circle:|com/starrocks/lake/LakeTablet.java|0|1|00.00%|[86]|
|:large_blue_circle:|com/starrocks/task/PushTask.java|1|2|50.00%|[183]|
|:large_blue_circle:|com/starrocks/load/loadv2/SparkLoadJob.java|40|57|70.18%|[502, 503, 504, 505, 506, 509, 510, 511, 512, 513, 514, 516, 517, 518, 603, 604, 605]|

2022-08-26 03:16 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 41 / 77 (53.25%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|0|18|00.00%|[497, 498, 533, 534, 535, 536, 538, 539, 540, 542, 544, 545, 546, 548, 549, 550, 551, 553]|
|:large_blue_circle:|com/starrocks/lake/LakeTablet.java|0|1|00.00%|[86]|
|:large_blue_circle:|com/starrocks/task/PushTask.java|1|2|50.00%|[183]|
|:large_blue_circle:|com/starrocks/load/loadv2/SparkLoadJob.java|40|56|71.43%|[499, 500, 501, 502, 505, 506, 507, 508, 509, 510, 512, 513, 514, 599, 600, 601]|

2022-08-26 03:26 UTC, abc982627271 commented on be/src/storage/lake/spark_load.cpp
> +        LOG(INFO) << "process realtime vectorized push successfully. "
old code is the same as this

2022-08-26 04:46 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 41 / 77 (53.25%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|0|18|00.00%|[497, 498, 533, 534, 535, 536, 538, 539, 540, 542, 544, 545, 546, 548, 549, 550, 551, 553]|
|:large_blue_circle:|com/starrocks/lake/LakeTablet.java|0|1|00.00%|[86]|
|:large_blue_circle:|com/starrocks/task/PushTask.java|1|2|50.00%|[183]|
|:large_blue_circle:|com/starrocks/load/loadv2/SparkLoadJob.java|40|56|71.43%|[499, 500, 501, 502, 505, 506, 507, 508, 509, 510, 512, 513, 514, 599, 600, 601]|

2022-08-26 06:07 UTC, abc982627271 commented on be/src/storage/lake/spark_load.cpp
> +    LOG(INFO) << "tablet=" << cur_tablet.id() << ", file path=" << path
old logic is the same

2022-08-26 06:26 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 41 / 77 (53.25%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|0|18|00.00%|[497, 498, 533, 534, 535, 536, 538, 539, 540, 542, 544, 545, 546, 548, 549, 550, 551, 553]|
|:large_blue_circle:|com/starrocks/lake/LakeTablet.java|0|1|00.00%|[86]|
|:large_blue_circle:|com/starrocks/task/PushTask.java|1|2|50.00%|[183]|
|:large_blue_circle:|com/starrocks/load/loadv2/SparkLoadJob.java|40|56|71.43%|[499, 500, 501, 502, 505, 506, 507, 508, 509, 510, 512, 513, 514, 599, 600, 601]|

2022-08-26 08:16 UTC, wyb commented on be/src/storage/task/engine_batch_load_task.cpp
> +        ASSIGN_OR_RETURN(auto tablet, tablet_manager->get_tablet(request.tablet_id));
call `StarRocksMetrics::instance()->push_requests_fail_total.increment(1)` if get tablet failed.

2022-08-26 08:16 UTC, wyb commented on be/src/storage/task/engine_batch_load_task.cpp
> +            status = _init();
`_is_init` should be set and will be checked in `_process`.

2022-08-26 08:16 UTC, wyb commented on fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadJob.java
> +                                    for (Replica replica : allQueryableReplicas) {
Only need to send push task to primary backend.

2022-08-26 09:53 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 53 / 78 (67.95%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|0|18|00.00%|[497, 498, 533, 534, 535, 536, 538, 539, 540, 542, 544, 545, 546, 548, 549, 550, 551, 553]|
|:large_blue_circle:|com/starrocks/lake/LakeTablet.java|0|1|00.00%|[86]|
|:large_blue_circle:|com/starrocks/task/PushTask.java|1|2|50.00%|[183]|
|:large_blue_circle:|com/starrocks/load/loadv2/SparkLoadJob.java|52|57|91.23%|[499, 516, 591, 592, 593]|

2022-08-26 13:03 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 66 / 79 (83.54%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/LakeTablet.java|0|1|00.00%|[86]|
|:large_blue_circle:|com/starrocks/task/PushTask.java|1|2|50.00%|[183]|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|13|18|72.22%|[497, 498, 542, 545, 546]|
|:large_blue_circle:|com/starrocks/load/loadv2/SparkLoadJob.java|52|58|89.66%|[499, 516, 517, 592, 593, 594]|

2022-08-26 13:25 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 66 / 79 (83.54%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/LakeTablet.java|0|1|00.00%|[86]|
|:large_blue_circle:|com/starrocks/task/PushTask.java|1|2|50.00%|[183]|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|13|18|72.22%|[497, 498, 542, 545, 546]|
|:large_blue_circle:|com/starrocks/load/loadv2/SparkLoadJob.java|52|58|89.66%|[499, 516, 517, 592, 593, 594]|

2022-08-29 03:30 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 66 / 79 (83.54%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/LakeTablet.java|0|1|00.00%|[86]|
|:large_blue_circle:|com/starrocks/task/PushTask.java|1|2|50.00%|[183]|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|13|18|72.22%|[497, 498, 542, 545, 546]|
|:large_blue_circle:|com/starrocks/load/loadv2/SparkLoadJob.java|52|58|89.66%|[499, 516, 517, 592, 593, 594]|

2022-08-29 03:37 UTC, wyb commented on fe/fe-core/src/main/java/com/starrocks/load/loadv2/SparkLoadJob.java
> +                                            backend, new Replica(tableId, backendId, 0, null),
```suggestion
                                            backend, new Replica(tabletId, backendId, 0, null),
```

2022-08-29 03:37 UTC, wyb commented on fe/fe-core/src/main/java/com/starrocks/leader/LeaderImpl.java
> +            return allQueryableReplicas.get(0);
```suggestion
            return new Replica(tablet id, backend id, -1, normal);
```

2022-08-29 03:37 UTC, wyb commented on fe/fe-core/src/main/java/com/starrocks/lake/LakeTablet.java
> +            Replica replica = new Replica(getId(), backendId, -1, null);
```suggestion
            Replica replica = new Replica(getId(), backendId, -1, normal);
```

2022-08-29 03:46 UTC, wyb commented on be/src/storage/task/engine_batch_load_task.cpp
> +        DCHECK(!_push_req.__isset.http_file_path);
Both local and lake tablets should check.

2022-08-29 07:33 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 62 / 74 (83.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/LakeTablet.java|0|1|00.00%|[88]|
|:large_blue_circle:|com/starrocks/task/PushTask.java|1|2|50.00%|[183]|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|9|13|69.23%|[498, 499, 539, 540]|
|:large_blue_circle:|com/starrocks/load/loadv2/SparkLoadJob.java|52|58|89.66%|[499, 516, 517, 592, 593, 594]|

2022-08-29 12:46 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 57 / 69 (82.61%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/LakeTablet.java|0|1|00.00%|[88]|
|:large_blue_circle:|com/starrocks/task/PushTask.java|1|2|50.00%|[183]|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|9|13|69.23%|[498, 499, 539, 540]|
|:large_blue_circle:|com/starrocks/load/loadv2/SparkLoadJob.java|47|53|88.68%|[499, 508, 509, 593, 594, 595]|

2022-08-30 02:59 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 63 / 76 (82.89%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/LakeTablet.java|0|1|00.00%|[88]|
|:large_blue_circle:|com/starrocks/task/PushTask.java|1|2|50.00%|[183]|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|9|13|69.23%|[498, 499, 539, 540]|
|:large_blue_circle:|com/starrocks/load/loadv2/SparkLoadJob.java|53|60|88.33%|[499, 516, 517, 526, 598, 599, 600]|

2022-08-30 03:23 UTC, wyb approved these changes

2022-08-30 03:43 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 63 / 76 (82.89%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/LakeTablet.java|0|1|00.00%|[88]|
|:large_blue_circle:|com/starrocks/task/PushTask.java|1|2|50.00%|[183]|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|9|13|69.23%|[498, 499, 539, 540]|
|:large_blue_circle:|com/starrocks/load/loadv2/SparkLoadJob.java|53|60|88.33%|[501, 518, 519, 528, 600, 601, 602]|

2022-08-30 06:34 UTC, sduzh approved these changes

2022-08-30 06:35 UTC, wanpengfei-git commented
run starrocks_admit_test

2022-08-30 11:09 UTC, merged