[Bugfix] Fix bug create MV with explain query and add compatibility
StarRocks/starrocks pull request #10423
Opened 2022-08-25 07:45 UTC by Astralidea

## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10347

## Problem Summary(Required) ：

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

2022-08-25 07:48 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 5 (20.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/common/MetaUtils.java|0|3|00.00%|[125, 129, 132]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|1|2|50.00%|[1186]|

2022-08-25 08:18 UTC, ABingHuang requested changes

2022-08-25 08:18 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/sql/common/MetaUtils.java
> +            LOG.warn("error happens when parsing create materialized view stmt use old parser:" +
```suggestion
            LOG.warn("error happens when parsing create materialized view stmt:{} use old parser" +
```

2022-08-25 08:26 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 6 (16.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/common/MetaUtils.java|0|4|00.00%|[113, 126, 130, 133]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|1|2|50.00%|[1186]|

2022-08-25 09:01 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 6 (16.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/common/MetaUtils.java|0|4|00.00%|[112, 125, 129, 132]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|1|2|50.00%|[1186]|

2022-08-25 09:14 UTC, ABingHuang approved these changes, later dismissed
LGTM

2022-08-25 09:20 UTC, gengjun-git approved these changes, later dismissed

2022-08-25 09:21 UTC, wanpengfei-git commented
run starrocks_admit_test

2022-08-25 11:48 UTC, HangyuanLiu commented on fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
> +            throw new IllegalArgumentException("Materialized view does not support explain query");
AstBuilder is to build ast node, Semantic check should add to xxxAnalyzer

2022-08-26 06:34 UTC, HangyuanLiu approved these changes

2022-08-26 06:35 UTC, gengjun-git approved these changes

2022-08-26 06:35 UTC, merged

2022-08-26 06:44 UTC, Astralidea commented
@Mergifyio backport branch-2.4

2022-08-26 06:57 UTC, Astralidea commented
@Mergifyio backport branch-2.3