[BugFix] Fix condition will always be true error when check functionset name in mv
StarRocks/starrocks pull request #10459
Opened 2022-08-26 07:26 UTC by caneGuy

## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

2022-08-26 07:28 UTC, caneGuy commented
@Astralidea @ABingHuang PTAL thanks

2022-08-26 07:29 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java|0|1|00.00%|[680]|

2022-08-26 08:01 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java
> +                    return !(fnName.equals(FunctionSet.COUNT) || fnName.equals(FunctionSet.SUM))
better to add UT cover this case

2022-08-31 08:40 UTC, Astralidea submitted a review, later dismissed

2022-08-31 14:24 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java|7|7|100.00%|[]|

2022-09-01 02:42 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java|7|7|100.00%|[]|

2022-09-01 02:57 UTC, caneGuy commented
run starrocks_admit_test

2022-09-01 03:00 UTC, Astralidea submitted a review, later dismissed

2022-09-01 06:34 UTC, ABingHuang requested changes

2022-09-01 06:34 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java
> +                    if (candidateIndexMeta.getKeysType() == KeysType.AGG_KEYS && !queryExprList.stream()
why move it here?
what is queryExpr0 for? seems useless?

2022-09-01 06:54 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java|1|1|100.00%|[]|

2022-09-01 06:55 UTC, Astralidea approved these changes

2022-09-05 06:39 UTC, ABingHuang approved these changes
LGTM

2022-09-05 06:39 UTC, wanpengfei-git commented
run starrocks_admit_test

2022-09-05 09:20 UTC, dirtysalt approved these changes

2022-09-05 09:20 UTC, merged

2022-09-05 09:25 UTC, Astralidea commented
@Mergifyio backport branch-2.4