[Bugfix]refresh after drop partition with data
StarRocks/starrocks pull request #10481
Opened 2022-08-26 11:14 UTC by smartlxh

## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9987

## Problem Summary(Required) ：

did not refresh after drop partition with data
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

2022-08-26 11:20 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 5 / 7 (71.43%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|5|7|71.43%|[1443, 1444]|

2022-08-28 14:48 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 5 / 9 (55.56%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|5|9|55.56%|[1442, 1443, 1446, 1447]|

2022-08-29 02:35 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
> +                    MaterializedView materializedView = (MaterializedView) db.getTable(mvId);
materializedView may got null better to check this

2022-08-29 02:40 UTC, ABingHuang requested changes

2022-08-29 02:40 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
> +                throw new DdlException(e.getMessage());
```suggestion
                throw new DdlException(“fail to refresh materialized views when dropping partition”, e);
```

2022-08-29 02:53 UTC, smartlxh commented
run starrocks_fe_unittest

2022-08-29 02:59 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 5 / 9 (55.56%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|5|9|55.56%|[1442, 1443, 1446, 1447]|

2022-08-29 03:01 UTC, Astralidea approved these changes

2022-08-29 06:57 UTC, ABingHuang approved these changes
LGTM

2022-08-29 06:58 UTC, wanpengfei-git commented
run starrocks_admit_test

2022-08-29 08:12 UTC, Astralidea commented
run starrocks_admit_test

2022-08-29 10:55 UTC, Astralidea commented
run starrocks_admit_test

2022-08-30 01:57 UTC, decster approved these changes

2022-08-30 01:57 UTC, merged

2022-08-30 01:58 UTC, Astralidea commented
@Mergifyio backport branch-2.4

2022-08-30 02:21 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|3|3|100.00%|[]|