[UT]Fix ColocateTableBalancerTest fail accidentally bug
StarRocks/starrocks pull request #11858
Opened 2022-09-29 12:20 UTC by gengjun-git

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [x] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

UT fails accidentally with error:
Missing 1 invocation to:
 com.starrocks.system.SystemInfoService#getIdToBackend()
This can occur in a high pressure environment. To fix this quickly, we call this method by hand.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

2022-09-29 12:33 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

2022-09-30 22:31 UTC, chaoyli requested changes

2022-09-30 22:31 UTC, chaoyli commented on fe/fe-core/src/test/java/com/starrocks/clone/ColocateTableBalancerTest.java
> +        GlobalStateMgr.getCurrentSystemInfo().getIdToBackend();
Please add a clear commit message about the pr and obey the format of title

2022-10-12 10:53 UTC, Astralidea approved these changes

2022-10-27 08:06 UTC, closed without merging