[Enhancement] generate min/max predicate from runtime filter & support `eval_with_filter`
StarRocks/starrocks pull request #12385
Opened 2022-10-23 01:12 UTC by dirtysalt

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

This PR introduces two things:
1. `evaluate_with_filter` in expr.
2.  generate min/max predicate from runtime filter.

About point 1, we can think about a case that. If we have two predicates:
1.  a > 10 (light weight operation)
2. function(b) > 100 ( heavy weight operation)
If we don't have `evaluate_with_filter`, for every tuple we have to run `function(b) > 100` even this tuple has been filtered by `a > 10`.  

SSB-100G with block cache

  | Before | After
-- | -- | --
Q01 | 641 | 418
Q02 | 596 | 359
Q03 | 529 | 342
Q04 | 894 | 915
Q05 | 760 | 798
Q06 | 719 | 778
Q07 | 1407 | 1400
Q08 | 856 | 910
Q09 | 757 | 848
Q10 | 726 | 476
Q11 | 1591 | 1582
Q12 | 1283 | 1077
Q13 | 1187 | 963
SUM | 11946 | 10866

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

2022-10-23 01:56 UTC, wanpengfei-git commented
starrocks_be_unittest succeeded.

2022-10-23 06:24 UTC, wanpengfei-git commented
starrocks_be_unittest succeeded.

2022-10-24 02:27 UTC, DorianZheng requested changes

2022-10-24 02:27 UTC, DorianZheng commented on be/src/exprs/vectorized/in_const_predicate.hpp
> +                        data3[row] = check_value_existence<use_array>(data[row]);
```
data3[row] = (filter[row] && check_value_existence<use_array>(data[row]));
```

2022-10-24 02:30 UTC, DorianZheng commented
which contributes to the performance improvement and which contributes to the performance degrade

2022-10-24 02:36 UTC, dirtysalt commented
> which contributes to the performance improvement and which contributes to the performance degrade

If min/max predicate filter more tuples than overhead of min/max predicate filter. then performance improves, otherwise performance degrades.

Two changes must comes together: min/max predicate without `evaluate_with_filter` has no meaning.

2022-10-24 02:40 UTC, dirtysalt commented on be/src/exprs/vectorized/in_const_predicate.hpp
> +                        data3[row] = check_value_existence<use_array>(data[row]);
OK. fixed.

2022-10-24 03:37 UTC, DorianZheng commented on be/src/exprs/vectorized/runtime_filter_bank.cpp
> +                res[i] = res[i] & filter[i];
why not use memcpy

2022-10-24 03:37 UTC, DorianZheng commented on be/src/exprs/vectorized/runtime_filter_bank.cpp
> +                res[i] = res[i] & (null_data[i] | (data[i] >= _min_value && data[i] <= _max_value));
will below more effective?
```
res[i] = res[i] && (null_data[i] || (data[i] >= _min_value && data[i] <= _max_value));
```

2022-10-24 03:37 UTC, DorianZheng commented on be/src/exprs/vectorized/runtime_filter_bank.cpp
> +                res[i] = res[i] & (data[i] >= _min_value && data[i] <= _max_value);
will below more effective?
```
res[i] = res[i] && (data[i] >= _min_value && data[i] <= _max_value);
```

2022-10-24 03:41 UTC, DorianZheng commented
seems q09 perf degrades a lot, should investigate more when times allowed

2022-10-24 03:46 UTC, dirtysalt commented on be/src/exprs/vectorized/runtime_filter_bank.cpp
> +                res[i] = res[i] & filter[i];
Right. we can use mempcy here.

2022-10-24 03:46 UTC, dirtysalt commented on be/src/exprs/vectorized/runtime_filter_bank.cpp
> +                res[i] = res[i] & (null_data[i] | (data[i] >= _min_value && data[i] <= _max_value));
Yes, short circuit works.

2022-10-24 05:08 UTC, wanpengfei-git commented
starrocks_be_unittest succeeded.

2022-10-24 08:47 UTC, DorianZheng approved these changes, later dismissed
LGTM

2022-10-29 13:01 UTC, wanpengfei-git commented
starrocks_be_unittest succeeded.

2022-10-29 23:26 UTC, wanpengfei-git commented
starrocks_be_unittest succeeded.

2022-10-31 03:05 UTC, dirtysalt commented
-----

__NOTE(yan):__ make sure `MinMaxPredicate::evaluate_with_filter` can be compiled into SIMD instructions.

original version, it's not.

```cpp
        if (filter != nullptr) {
            memcpy(res, filter, size);
        }

        if (col->is_nullable()) {
            auto tmp = ColumnHelper::as_raw_column<NullableColumn>(col);
            uint8_t* null_data = tmp->null_column_data().data();
            CppType* data = ColumnHelper::cast_to_raw<Type>(tmp->data_column())->get_data().data();
            for (int i = 0; i < size; i++) {
                res[i] = res[i] && (null_data[i] || (data[i] >= _min_value && data[i] <= _max_value));
            }
        } else {
            CppType* data = ColumnHelper::cast_to_raw<Type>(col)->get_data().data();
            for (int i = 0; i < size; i++) {
                res[i] = res[i] && (data[i] >= _min_value && data[i] <= _max_value);
            }
        }
```

<img width="503" alt="mov -0x70(rbp),rbx" src="https://user-images.githubusercontent.com/1081215/198831370-06835a25-bc8a-4d28-a36d-13e77ef4e547.png">

but current version yes.

```cpp
        // NOTE(yan): make sure following code can be compiled into SIMD instructions:
        // in original version, we use
        // 1. memcpy filter -> res
        // 2. res[i] = res[i] && (null_data[i] || (data[i] >= _min_value && data[i] <= _max_value));
        // but they can not be compiled into SIMD instructions.
        if (col->is_nullable()) {
            auto tmp = ColumnHelper::as_raw_column<NullableColumn>(col);
            uint8_t* __restrict__ null_data = tmp->null_column_data().data();
            CppType* __restrict__ data = ColumnHelper::cast_to_raw<Type>(tmp->data_column())->get_data().data();
            for (int i = 0; i < size; i++) {
                res[i] = (data[i] >= _min_value && data[i] <= _max_value);
            }
            for (int i = 0; i < size; i++) {
                res[i] = res[i] | null_data[i];
            }
        } else {
            CppType* data = ColumnHelper::cast_to_raw<Type>(col)->get_data().data();
            for (int i = 0; i < size; i++) {
                res[i] = (data[i] >= _min_value && data[i] <= _max_value);
            }
        }

        if (filter != nullptr) {
            for (int i = 0; i < size; i++) {
                res[i] = res[i] & filter[i];
            }
        }
```

<img width="836" alt="Pasted Graphic 7" src="https://user-images.githubusercontent.com/1081215/198831376-04e2f4c2-9524-4be7-9e7c-9415a9ba0d37.png">

2022-10-31 03:27 UTC, Seaven commented
> ```c++
>                 res[i] = res[i] && (null_data[i] || (data[i] >= _min_value && data[i] <= _max_value));
> ```

Logical operator will forbidden auto simd

2022-10-31 05:10 UTC, dirtysalt commented
> > ```c++
> >                 res[i] = res[i] && (null_data[i] || (data[i] >= _min_value && data[i] <= _max_value));
> > ```
> 
> Logical operator can't auto-simd, and you can test
> 
> ```
>                 res[i] = (data[i] >= _min_value & data[i] <= _max_value);
> ```

yes, you are right. this version can compiled into SIMD version.

2022-11-03 07:40 UTC, zombee0 approved these changes, later dismissed
LGTM

2022-11-04 02:23 UTC, Youngwb approved these changes, later dismissed

2022-11-04 05:51 UTC, stephen-shelby approved these changes, later dismissed

2022-11-04 05:57 UTC, caneGuy submitted a review, later dismissed

2022-11-04 05:57 UTC, dirtysalt commented
run starrocks_admit_test

2022-11-04 08:17 UTC, dirtysalt commented
run starrocks_admit_test

2022-11-05 01:18 UTC, dirtysalt commented
run starrocks_admit_test

2022-11-05 10:59 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

2022-11-05 11:25 UTC, dirtysalt commented
run starrocks_admit_test

2022-11-05 11:34 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

2022-11-05 12:14 UTC, satanson approved these changes

2022-11-05 12:22 UTC, gengjun-git approved these changes

2022-11-05 12:23 UTC, merged