[Feature][WIP] Support to write/read binlog
StarRocks/starrocks pull request #15177
Opened 2022-12-14 03:23 UTC by banmoy

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

2022-12-15 06:41 UTC, LiShuMing commented on be/src/storage/binlog_file_reader.h
> +
Is there an api to get  the consumed `seq_id`?

2022-12-15 06:41 UTC, LiShuMing commented on be/src/storage/binlog_file_reader.cpp
> +        : _file_path(std::move(file_name)), _file_meta(file_meta) {}
Why not `std::move(file_meta)`?  `file_meta` is shared across what?

2022-12-15 06:41 UTC, LiShuMing commented on be/src/storage/binlog_file_reader.cpp
> +            return Status::NotFound(strings::Substitute("Can't find version $0", version));
`fmt::format` is better? Add `page_header_pb.version()` in the error msg to debug?

2022-12-15 06:41 UTC, LiShuMing commented on be/src/storage/binlog_file_reader.cpp
> +        if (_next_page_index == _file_meta->num_pages()) {
Is `if (_next_page_index + 1 == _file_meta->num_pages()) {` ?

2022-12-15 06:41 UTC, LiShuMing commented on be/src/storage/binlog_file_reader.cpp
> +Status BinlogFileReader::next() {
Why not `Status next(LogEntryInfo* result_log_entry)` ?

2022-12-15 06:41 UTC, LiShuMing commented on be/src/storage/binlog_reader.cpp
> +    chunk->get()->reset();
`chunk->get()->reset();` maybe not needed, `chunk` should be a new object?

2022-12-15 06:41 UTC, LiShuMing commented on be/src/storage/binlog_reader.cpp
> +    auto res = seg_ptr->new_iterator(_schema, seg_options);
Can the same `_segment_iterator ` (the same segment file) be initialized multi time? maybe reuse _segment_iterator later?

2022-12-15 06:41 UTC, LiShuMing commented on be/src/storage/binlog_reader.cpp
> +    auto res = seg_ptr->new_iterator(_schema, seg_options);
Does `new_iterator `  open other index files other than segment file?

2022-12-15 06:41 UTC, LiShuMing commented on be/src/storage/binlog_reader.cpp
> +    // TODO append binlog meta columns
How to add binlog meta?  Does BinlogReader support `filter`?

This maybe a problem, or `BinlogReader` just not support filter, always output full schema?

2022-12-17 04:30 UTC, mofeiatwork commented on be/src/storage/binlog_manager.cpp
> +    std::lock_guard lock(_write_lock);
such a big lock

2022-12-17 04:30 UTC, mofeiatwork commented on be/src/storage/binlog_manager.cpp
> +                std::shared_ptr<BinlogFileWriter> writer = pending_writers[i];
Use reference to avoid copy `shared_ptr` ?

2022-12-17 04:30 UTC, mofeiatwork commented on be/src/storage/binlog_manager.cpp
> +        if (VLOG_IS_ON(3)) {
?

2022-12-17 04:30 UTC, mofeiatwork commented on be/src/storage/binlog_manager.cpp
> +                LOG(WARNING) << "Fail to abort binlog writer " << writer->file_name();
how to handle this error ?

2022-12-17 04:30 UTC, mofeiatwork commented on be/src/storage/binlog_manager.cpp
> +void BinlogManager::delete_expired_binlog() {
is there any daemon thread to do this work ?

2022-12-17 04:30 UTC, mofeiatwork commented on be/src/storage/binlog_manager.cpp
> +    st = fs->delete_file(file_path);
How to handle the delete failure

2023-01-03 12:33 UTC, ABingHuang requested changes

2023-01-03 12:33 UTC, ABingHuang commented on be/src/storage/binlog_file_writer.cpp
> +    bool in_one_segment = false;
```suggestion
    bool in_one_segment = page_context->last_segment_index == seg_index;
```

2023-01-03 12:33 UTC, ABingHuang commented on be/src/storage/binlog_file_writer.cpp
> +    if (page_context->last_segment_index != seg_index) {
```suggestion
    if (!in_one_segment) {
```

2023-01-03 12:33 UTC, ABingHuang commented on be/src/storage/binlog_file_writer.h
> +    int32_t last_row_id;
is it inclusive or exclusive?

2023-01-03 12:33 UTC, ABingHuang commented on be/src/storage/binlog_file_writer.h
> +    int64_t end_seq_id;
what are these first two fields used for?

2023-01-03 12:33 UTC, ABingHuang commented on gensrc/proto/binlog.proto
> +  optional int64 end_seq_id = 9;
what are start_seq_id and end_seq_id used for?

2023-01-03 12:33 UTC, ABingHuang commented on be/src/storage/binlog_file_writer.h
> +    int64_t version;
does version stand for epoch for binlog?

2023-01-03 12:33 UTC, ABingHuang commented on be/src/storage/binlog_file_writer.cpp
> +    _writer_state = WAIT_WRITE;
why state changed to WAIT_WRITE after commit?

2023-01-04 07:25 UTC, ABingHuang commented on be/src/storage/binlog_file_writer.cpp
> +        _set_file_id_pb(_pending_version_context->rowset_id, seg_index, entry_data->mutable_file_id());
how to make sure the original data in rowset_id and seg_index still exist after compaction?
where to realize this logic?

2023-01-04 07:25 UTC, ABingHuang commented on be/src/storage/binlog_file_reader.cpp
> +        InsertRangePB* entry_data = next_log_entry->mutable_insert_range_data();
mutable_xx is used to write. I think we need to read. should call next_log_entry->insert_range_data() here?

2023-01-11 10:52 UTC, closed without merging