[Refactor] refactor dict filter logic in group reader
StarRocks/starrocks pull request #15471
Opened 2022-12-20 07:28 UTC by dirtysalt

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

This PR is to refactor dict filter logic: wrap dict filter related code into `DictFilterContext`.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

2022-12-20 14:28 UTC, DorianZheng commented on be/src/formats/parquet/group_reader.cpp
> +        _dict_filter_ctx.filter_chunk(&active_chunk, &chunk_filter);
It's more simple if we let `filter_chunk` return bool value to indicate if it has predicates, then we don't need `has_predicates`

2022-12-20 14:30 UTC, DorianZheng commented on be/src/formats/parquet/group_reader.cpp
> +Status GroupReader::_process_columns_and_conjunct_ctxs() {
It's always return `Status::OK()`. It seems OK to remain returning `void` type

2022-12-20 14:34 UTC, DorianZheng commented on be/src/formats/parquet/group_reader.h
> +        GroupReader* _parent = nullptr;
It's too much. Could you pass what is real needed.

2022-12-20 14:35 UTC, DorianZheng commented on be/src/formats/parquet/group_reader.cpp
> +    const GroupReaderParam& _param = _parent->_param;
pass param as a const reference

2022-12-20 14:35 UTC, DorianZheng commented on be/src/formats/parquet/group_reader.cpp
> +        RETURN_IF_ERROR(_parent->_column_readers[slot_id]->get_dict_values(dict_value_column.get()));
pass column readers as a const reference

2022-12-20 14:36 UTC, DorianZheng commented on be/src/formats/parquet/group_reader.cpp
> +    size_t chunk_size = _parent->_param.chunk_size;
pass chunk size as a argument

2022-12-20 14:36 UTC, DorianZheng commented on be/src/formats/parquet/group_reader.cpp
> +        const auto& column = _parent->_param.read_cols[col_idx];
pass read_cols as a argument

2022-12-20 14:36 UTC, DorianZheng commented on be/src/formats/parquet/group_reader.cpp
> +    const GroupReaderParam& _param = _parent->_param;
ditto

2022-12-20 14:36 UTC, DorianZheng requested changes

2022-12-20 14:36 UTC, DorianZheng commented on be/src/formats/parquet/group_reader.cpp
> +                    _parent->_column_readers[slot_id]->get_dict_values(codes_column->get_data(), dict_values.get()));
ditto

2022-12-23 06:43 UTC, DorianZheng approved these changes

2022-12-26 02:22 UTC, stephen-shelby approved these changes

2022-12-26 02:23 UTC, wanpengfei-git commented
run starrocks_admit_test

2022-12-26 03:14 UTC, Youngwb approved these changes

2022-12-26 03:15 UTC, merged