[Feature]Binlog show create table
StarRocks/starrocks pull request #16361
Opened 2023-01-09 05:29 UTC by smartlxh

## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

supporting show binlog propeties by sql `show create table table_name`

![image](https://user-images.githubusercontent.com/13373748/211245724-cd2d5ae7-8431-426d-ae6a-9ed338672f12.png)

![image](https://user-images.githubusercontent.com/13373748/211245702-ad408414-e812-4fdb-968d-7c6694eabcdd.png)

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

2023-01-09 06:01 UTC, mofeiatwork approved these changes, later dismissed

2023-01-09 06:13 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 2 / 19 (10.53%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|1|18|05.56%|[2289, 2290, 2291, 2292, 2293, 2295, 2296, 2297, 2298, 2300, 2301, 2302, 2303, 2305, 2306, 2307, 2308]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|1|1|100.00%|[]|

2023-01-09 06:49 UTC, caneGuy commented on fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
> -        boolean enableBinlog = PropertyAnalyzer.analyzeBooleanProp(properties, PropertyAnalyzer.PROPERTIES_BINLOG_ENABLE, false);
add some description in the pr summary

2023-01-09 06:49 UTC, caneGuy commented on fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
> +                        PropertyAnalyzer.PROPERTIES_BINLOG_ENABLE, false);
refine log below

2023-01-09 06:49 UTC, caneGuy commented on fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
> +                if (olapTable.isHaveBinlogConfig()) {
isHaveBinlogConfig -> containsBinlogConfig

2023-01-09 06:50 UTC, caneGuy requested changes

2023-01-09 06:50 UTC, caneGuy commented on fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
>                          properties.containsKey(PropertyAnalyzer.PROPERTIES_BINLOG_TTL))) {
nit: i think we should check binlog_enable first

2023-01-09 11:59 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 9 / 27 (33.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|1|18|05.56%|[2289, 2290, 2291, 2292, 2293, 2295, 2296, 2297, 2298, 2300, 2301, 2302, 2303, 2305, 2306, 2307, 2308]|
|:large_blue_circle:|com/starrocks/binlog/BinlogManager.java|2|3|66.67%|[78]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/leader/ReportHandler.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|1|1|100.00%|[]|

2023-01-10 05:03 UTC, smartlxh commented on fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
> +                        PropertyAnalyzer.PROPERTIES_BINLOG_ENABLE, false);
I will fix this in another pr

2023-01-10 05:12 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 2 / 19 (10.53%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|1|18|05.56%|[2289, 2290, 2291, 2292, 2293, 2295, 2296, 2297, 2298, 2300, 2301, 2302, 2303, 2305, 2306, 2307, 2308]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|1|1|100.00%|[]|

2023-01-11 06:46 UTC, caneGuy approved these changes

2023-01-11 06:48 UTC, mofeiatwork approved these changes

2023-01-11 06:49 UTC, wanpengfei-git commented
run starrocks_admit_test

2023-01-11 07:34 UTC, smartlxh commented
run starrocks_admit_test

2023-01-11 07:38 UTC, smartlxh commented
run starrocks_admit_test

2023-01-11 08:15 UTC, merged