[BugFix] Fix some compatibility for auto increment column (#18443)
StarRocks/starrocks pull request #18444
Opened 2023-02-24 03:24 UTC by srlch

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #18443

## Problem Summary(Required) ：
Problem:
1. Some new metadata persisted in BackupMeta which incompatible with older versions.
2. Auto-increment param in OlapTableSink will be init uncorrectly when FE is older versions.

Solution:
1. persist the new metadata for backup in BackupJobInfo, which is JSON stored in remote but not in Image File.
2. Check Fe version when init param in OlapTableSink.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

2023-02-24 09:20 UTC, decster submitted a review, later dismissed

2023-02-27 06:05 UTC, srlch commented
run starrocks_be_unittest

2023-02-27 06:05 UTC, srlch commented
run starrocks_fe_unittest

2023-02-27 06:10 UTC, gengjun-git approved these changes, later dismissed

2023-02-27 06:11 UTC, wanpengfei-git commented
run starrocks_admit_test

2023-02-27 06:39 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 9 / 17 (52.94%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/backup/BackupJobInfo.java|9|17|52.94%|[172, 174, 175, 177, 326, 327, 414, 418]|

2023-02-28 02:16 UTC, ABingHuang requested changes

2023-02-28 02:16 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/backup/BackupJobInfo.java
> +                LOG.info("read from older BackJobInfo.");
```suggestion
                LOG.warn("read from older BackJobInfo.", e);
```

2023-03-01 10:39 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 16 / 26 (61.54%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/backup/RestoreJob.java|0|2|00.00%|[494, 606]|
|:large_blue_circle:|com/starrocks/backup/BackupJobInfo.java|9|17|52.94%|[172, 174, 175, 177, 326, 327, 414, 418]|
|:large_blue_circle:|com/starrocks/catalog/Database.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|1|1|100.00%|[]|

2023-03-01 11:46 UTC, gengjun-git approved these changes

2023-03-02 03:39 UTC, chaoyli approved these changes

2023-03-02 03:40 UTC, wanpengfei-git commented
run starrocks_admit_test

2023-03-02 05:34 UTC, srlch commented on fe/fe-core/src/main/java/com/starrocks/backup/BackupJobInfo.java
> +                LOG.info("read from older BackJobInfo.");
done

2023-03-02 06:18 UTC, ABingHuang approved these changes

2023-03-02 06:21 UTC, merged

2023-03-02 06:22 UTC, wanpengfei-git commented
@Mergifyio backport branch-3.0