[Enhancement] Use conflict detection + shallow copy to avoid db lock when query plan
StarRocks/starrocks pull request #18608
Opened 2023-02-28 03:42 UTC by kangkaisen

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：
When there are a lot of partitions and tablets, the olaptable deep copy need a lot of time. mainly for idToPartition and partitionInfo, in fact, for idToPartition and partitionInfo, shallow copy is enough.

After this PR, in the ReplayFromDumpTest.testManyPartitions UT, the copt time from 3s to 3ms.

**1， we use conflict detection to ensure multi partition visible versions are consistent**

**2， we use conflict detection to check the schema change when query plan**

**3， we use shallow copy to avoid the ConcurrentModificationException of olap table maps**

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

2023-02-28 10:46 UTC, packy92 submitted a review, later dismissed

2023-02-28 10:47 UTC, liuyehcf submitted a review, later dismissed

2023-02-28 10:48 UTC, wanpengfei-git commented
run starrocks_admit_test

2023-02-28 11:02 UTC, Seaven submitted a review, later dismissed

2023-02-28 15:56 UTC, ABingHuang requested changes

2023-02-28 15:56 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java
> +        olapTable.idToPartition = Maps.newHashMap(this.idToPartition);
partition should also need deep copy
because partition's version is important to realize mvcc.

2023-02-28 18:47 UTC, mofeiatwork commented
run starrocks_fe_unittest

2023-02-28 18:59 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 38 / 40 (95.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/TableProperty.java|6|8|75.00%|[174, 175]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|23|23|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/RangePartitionInfo.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|1|1|100.00%|[]|

2023-03-02 11:45 UTC, Seaven submitted a review, later dismissed

2023-03-02 12:40 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 104 / 108 (96.30%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/TableProperty.java|6|8|75.00%|[174, 175]|
|:large_blue_circle:|com/starrocks/sql/StatementPlanner.java|35|37|94.59%|[216, 218]|
|:large_blue_circle:|com/starrocks/alter/Alter.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|25|25|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/RangePartitionInfo.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/transaction/OlapTableTxnLogApplier.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|16|16|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|1|1|100.00%|[]|

2023-03-02 13:11 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/catalog/RangePartitionInfo.java
> +        super(PartitionType.RANGE);
```suggestion
        super(other.getType());
```
The automatic partition will use PartitionType.EXPR_RANGE

2023-03-02 13:18 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java
> +            super((tables));
Why 2 times in parentheses?

2023-03-03 02:58 UTC, Astralidea submitted a review, later dismissed

2023-03-06 04:46 UTC, Astralidea approved these changes

2023-03-06 07:30 UTC, Seaven approved these changes

2023-03-06 07:31 UTC, wanpengfei-git commented
run starrocks_admit_test

2023-03-06 07:32 UTC, merged

2023-03-06 07:32 UTC, wanpengfei-git commented
@Mergifyio backport branch-3.0