[BugFix]modify array_agg with sub error messages
StarRocks/starrocks pull request #19215
Opened 2023-03-08 08:29 UTC by leoyy0316

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19198

## Problem Summary(Required) ：

fix after:
![image](https://user-images.githubusercontent.com/105328124/223661831-3adc2420-b9d0-40f7-976a-124ca7f6c2f6.png)
![image](https://user-images.githubusercontent.com/105328124/223662070-46813508-85dc-4d67-a5bf-5009364fdd02.png)

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

2023-03-08 09:10 UTC, stephen-shelby approved these changes, later dismissed

2023-03-08 09:12 UTC, leoyy0316 commented
run starrocks_admit_test

2023-03-08 09:14 UTC, Youngwb approved these changes, later dismissed

2023-03-08 09:34 UTC, Seaven requested changes
I think we should to find why array can be cast to double/bigint, not throw expcetion direct

2023-03-08 11:09 UTC, leoyy0316 commented
> I think we should to find why array can be cast to double/bigint, not throw expcetion direct

ok, will check it

2023-03-09 05:33 UTC, leoyy0316 commented
> I think we should to find why array can be cast to double/bigint, not throw expcetion direct

@Seaven  i check it , not cast to double/int, in [visitArithmeticExpr] when getCommonType return Type.INVALID

2023-03-09 05:34 UTC, leoyy0316 commented
run starrocks_fe_unittest

2023-03-09 05:43 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|3|3|100.00%|[]|

2023-03-09 06:49 UTC, Seaven commented
> > I think we should to find why array can be cast to double/bigint, not throw expcetion direct
> 
> @Seaven i check it , not cast to double/int, in [visitArithmeticExpr] when getCommonType return Type.INVALID

if common type is Type.INVALID, it's should check failed in line 626,  any type can't cast to Type.INVALID,  I think should to resolve this...

2023-03-09 07:01 UTC, Seaven commented
> > > > I think we should to find why array can be cast to double/bigint, not throw expcetion direct
> > > 
> > > 
> > > @Seaven i check it , not cast to double/int, in [visitArithmeticExpr] when getCommonType return Type.INVALID
> > 
> > 
> > if common type is Type.INVALID, it's should check failed in line 626, any type can't cast to Type.INVALID, I think should to resolve this question...
> 
> @Seaven ok, i will modify. Also i think fn need to check failed when is null, maybe cause NPE

to check function is the correct way, but function is null in here is an unexpected error, I suggest add `Precondition.check` directly

2023-03-09 07:30 UTC, leoyy0316 commented
> > > > > I think we should to find why array can be cast to double/bigint, not throw expcetion direct
> > > > 
> > > > 
> > > > @Seaven i check it , not cast to double/int, in [visitArithmeticExpr] when getCommonType return Type.INVALID
> > > 
> > > 
> > > if common type is Type.INVALID, it's should check failed in line 626, any type can't cast to Type.INVALID, I think should to resolve this question...
> > 
> > 
> > @Seaven ok, i will modify. Also i think fn need to check failed when is null, maybe cause NPE
> 
> check function is the correct way, but function is null in here is an unexpected error, I suggest add `Preconditions.checkNotNull(fn)` directly
@Seaven if use Preconditions.checkNotNull(fn), also wiil throw Unknown error in mysql client

2023-03-09 08:10 UTC, Seaven approved these changes, later dismissed

2023-03-09 08:10 UTC, leoyy0316 commented
run starrocks_admit_test

2023-03-09 08:16 UTC, leoyy0316 commented
run starrocks_fe_unittest

2023-03-09 08:43 UTC, leoyy0316 commented on fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java
> +                }
@Seaven yes, ut return error, modify it. done, thanks

2023-03-09 08:55 UTC, Seaven approved these changes, later dismissed

2023-03-10 02:53 UTC, Seaven commented
> @Seaven hi, when modify, some ut failed, can you help check this ut really need to check Type.INVALID to failed ? thanks

should move check from 621 to 629

2023-03-10 03:10 UTC, leoyy0316 commented
> > @Seaven hi, when modify, some ut failed, can you help check this ut really need to check Type.INVALID to failed ? thanks
> 
> should move check from line:621 to line:629

@Seaven  oh, i know, thanks

2023-03-10 03:13 UTC, leoyy0316 commented
run starrocks_admit_test

2023-03-10 03:17 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 2 / 3 (66.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|2|3|66.67%|[647]|

2023-03-10 03:24 UTC, leoyy0316 commented
run starrocks_admit_test

2023-03-10 04:27 UTC, leoyy0316 commented
run starrocks_admit_test

2023-03-10 05:22 UTC, leoyy0316 commented
run starrocks_admit_test

2023-03-10 08:15 UTC, Seaven approved these changes

2023-03-10 09:58 UTC, Youngwb approved these changes

2023-03-10 09:59 UTC, merged

2023-03-10 09:59 UTC, wanpengfei-git commented
run starrocks_admit_test