Add some meta about partial update to RowsetMetaPB
StarRocks/starrocks pull request #1958
Opened 2021-12-08 07:49 UTC by decster

2021-12-09 10:44 UTC, Astralidea approved these changes, later dismissed

2021-12-10 10:13 UTC, Linkerist approved these changes, later dismissed

2021-12-13 09:09 UTC, chaoyli requested changes

2021-12-13 09:09 UTC, chaoyli commented on gensrc/proto/olap_file.proto
> +    repeated string partial_update_columns = 1;
The use of column names is not a good idea.  It's better to use column_id instead.

2021-12-14 03:00 UTC, chaoyli approved these changes

2021-12-14 03:01 UTC, Astralidea approved these changes

2021-12-14 03:16 UTC, merged