Support partial row in read/write process for partial update.
StarRocks/starrocks pull request #2060
Opened 2021-12-10 12:38 UTC by Linkerist

Since partial update syntax supported in #1546 , #1829 , need to implement it in read/write process.
Use partial schema in write process, use full schema in read process, for unspecified columns, use default value.
for example, for this table:
```
CREATE TABLE test (
 `k1` date NOT NULL,
 `k2` datetime NOT NULL,
 `k3` string NOT NULL,
 `k4` string NOT NULL,
 `k5` boolean NOT NULL,
 `v1` tinyint NOT NULL,
 `v2` smallint NOT NULL default '0'
) ENGINE=OLAP PRIMARY KEY(`k1`, `k2`, `k3`, `k4`, `k5`) COMMENT "OLAP" DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3 PROPERTIES ( "replication_num" = "1", "storage_format" = "v2" );
```

2021-12-13 03:01 UTC, Linkerist commented
run starrocks_be_unittest

2021-12-13 13:23 UTC, decster requested changes

2021-12-13 13:23 UTC, decster commented on be/src/storage/rowset/rowset.h
> +    inline void set_full_tablet_schema(const TabletSchema* full_tablet_schema) { _schema = full_tablet_schema; }
just set_schema

2021-12-13 13:23 UTC, decster commented on be/src/storage/vectorized/delta_writer.cpp
> +            (*_req.slots).begin(), (*_req.slots).end() - ((*_req.slots).back()->col_name() == "__op"));
Could we avoid copying this vector?

2021-12-13 13:23 UTC, decster commented on be/src/storage/vectorized/delta_writer.cpp
> +        }
maybe create a new method for TabletSchema to create a new TabletSchema by specifying columns, and call that method instead.
std::shared_ptr<TabletSchema> TabletSchema::create(src_schema, column_names_or_ids)

2021-12-13 13:23 UTC, decster commented on be/src/storage/vectorized/delta_writer.cpp
> +
remove this

2021-12-14 06:47 UTC, decster submitted a review, later dismissed

2021-12-14 06:47 UTC, decster commented on be/src/storage/rowset/rowset.h
> +    inline void set_schema(const TabletSchema* full_tablet_schema) { _schema = full_tablet_schema; }
Also parameter name

2021-12-14 06:47 UTC, decster commented on be/src/storage/vectorized/delta_writer.cpp
> +        (end - begin) < _tablet->tablet_schema().num_columns()) {
Could you make it cleaner?

2021-12-14 12:49 UTC, decster approved these changes, later dismissed

2021-12-15 01:48 UTC, chaoyli commented on be/src/storage/vectorized/delta_writer.cpp
> +    std::size_t partial_col_num = (*_req.slots).size();
_req.slots->size() is ok

2021-12-15 01:48 UTC, chaoyli commented on be/src/storage/vectorized/delta_writer.cpp
> +        for (auto i = 0; i < partial_col_num; ++i) {
for (auto & slot_desc : *_req.slots)

2021-12-16 06:28 UTC, Linkerist commented
run starrocks_be_unittest

2021-12-16 08:23 UTC, decster approved these changes

2021-12-16 10:45 UTC, chaoyli approved these changes

2021-12-16 10:46 UTC, merged