[Doc] Update QuickStart
StarRocks/starrocks pull request #21263
Opened 2023-04-10 09:31 UTC by EsoragotoSpirit

Signed-off-by: EsoragotoSpirit <wanglichen@starrocks.com>

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [x] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

2023-04-10 10:44 UTC, ss892714028 requested changes

2023-04-10 10:44 UTC, ss892714028 commented on docs/quick_start/Deploy.md
> +  You can follow these steps on relatively elementary hardware, such as a machine with 4 CPU cores and 16 GB of RAM. In production, we recommend you run StarRocks with CPUs that support the AVX2 inst
The binary from SR's website does not support arm as well

2023-04-10 10:44 UTC, ss892714028 commented on docs/quick_start/Deploy.md
> +  Your machine MUST be running on CentOS 7.0 or later. To run StarRocks on other operating systems, you must [Deploy StarRocks in Docker](../quick_start/deploy_in_docker.md).
To run on Ubuntu 22.04 or with ARM-based processors, from [here](https://hub.docker.com/r/starrocks/allin1-ubuntu), find the tag, run the image, and copy the binaries from the docker container to your host machine.

2023-04-10 10:44 UTC, ss892714028 commented on docs/quick_start/Deploy.md
> +  Your machine MUST be running on CentOS 7.0 or later. To run StarRocks on other operating systems, you must [Deploy StarRocks in Docker](../quick_start/deploy_in_docker.md).
FE dir: /data/starrocks/fe/
BE dir: /data/starrocks/be/

2023-04-12 06:27 UTC, evelynzhaojie approved these changes

2023-04-12 06:29 UTC, amber-create approved these changes

2023-04-12 06:34 UTC, ss892714028 approved these changes

2023-04-12 06:35 UTC, merged

2023-04-12 06:35 UTC, wanpengfei-git commented
@Mergifyio backport branch-3.0

2023-04-12 06:35 UTC, wanpengfei-git commented
@Mergifyio backport branch-2.5