[BugFix] fix starosAgent NPE when replay trunate table after fe restart
StarRocks/starrocks pull request #22869
Opened 2023-05-05 09:30 UTC by abc982627271

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes:

Fixes #

## Problem Summary(Required):

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

2023-05-05 09:44 UTC, kevincai approved these changes

2023-05-05 11:22 UTC, imay approved these changes

2023-05-05 12:41 UTC, kevincai requested changes
could be problematic since the checkpoint thread touches starmgr non-checkpoint metadata. hold on the change for now.

2023-05-16 08:54 UTC, closed without merging

2023-05-16 08:54 UTC, wanpengfei-git commented
@Mergifyio backport branch-3.0