[BugFix] Fix query sync mv which mv's distribution keys don't match base table
StarRocks/starrocks pull request #23051
Opened 2023-05-09 06:34 UTC by LiShuMing

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Problem Summary(Required):

fix: https://github.com/StarRocks/starrocks/issues/22401

- Fix query sync mv which mv's distribution keys don't match base table

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

2023-05-09 06:54 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 18 / 20 (90.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|18|20|90.00%|[446, 448]|

2023-05-10 02:15 UTC, mofeiatwork approved these changes

2023-05-10 12:40 UTC, ABingHuang requested changes

2023-05-10 12:40 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
> +            DistributionSpec distributionSpec = getTableDistributionSpec(node, columnMetaToColRefMap);
is it useless?

2023-05-10 12:43 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/RelationTransformer.java
> +            DistributionSpec distributionSpec = getTableDistributionSpec(node, columnMetaToColRefMap);
move it into branch } else if (!isMVPlanner) {?

2023-05-10 12:43 UTC, ABingHuang approved these changes

2023-05-10 12:43 UTC, merged