[BugFix] Fix parquet page reader EOF check
StarRocks/starrocks pull request #25352
Opened 2023-06-15 06:35 UTC by letian-jiang

There are parquet files (although rare) where `total_uncompressed_bytes` in column chunk meta is larger than the total uncompressed bytes of all pages.

In this case, the current page reader would try to read an extra page (which is not existent), resulting in a page header decode error.

This PR resorts to `num_values` in column chunk meta, in line with `parquet-mr/parquet-cli`

```java
  private boolean hasMorePages(long valuesCountReadSoFar, int dataPageCountReadSoFar) {
    return offsetIndex == null ? valuesCountReadSoFar < descriptor.metadata.getValueCount()
        : dataPageCountReadSoFar < offsetIndex.getPageCount();
  }
```

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4

2023-06-16 03:54 UTC, DorianZheng approved these changes

2023-06-16 03:57 UTC, DorianZheng requested changes
please add UT

2023-06-20 06:10 UTC, letian-jiang commented on be/src/formats/parquet/page_reader.cpp
> +    if (_num_values_read == _num_values_total) {
done

2023-06-20 06:11 UTC, letian-jiang commented on be/test/formats/parquet/page_reader_test.cpp
> +//TEST_F(ParquetPageReaderTest, Normal) {
done

2023-06-20 08:11 UTC, Smith-Cruise commented on be/src/formats/parquet/page_reader.h
>      uint64_t _finish_offset = 0;
add const?

2023-06-20 08:51 UTC, Smith-Cruise approved these changes

2023-06-20 13:57 UTC, dirtysalt approved these changes

2023-06-21 17:23 UTC, stephen-shelby approved these changes

2023-06-21 17:23 UTC, merged

2023-06-21 17:23 UTC, wanpengfei-git commented
@Mergifyio backport branch-3.1

2023-06-21 17:23 UTC, wanpengfei-git commented
@Mergifyio backport branch-3.0

2023-06-21 17:23 UTC, wanpengfei-git commented
@Mergifyio backport branch-2.5