[Enhancement] Optimize generatePartitionRefMap performance when there are many partitions in base table
StarRocks/starrocks pull request #26824
Opened 2023-07-10 05:19 UTC by LiShuMing

Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

2023-07-10 06:22 UTC, Astralidea approved these changes, later dismissed

2023-07-10 06:47 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 39 / 40 (97.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/common/SyncPartitionUtils.java|39|40|97.50%|[92]|

2023-07-12 11:29 UTC, mofeiatwork submitted a review, later dismissed

2023-07-12 11:34 UTC, ABingHuang requested changes

2023-07-12 11:46 UTC, Astralidea submitted a review, later dismissed

2023-07-12 14:17 UTC, LiShuMing commented on fe/fe-core/src/main/java/com/starrocks/sql/common/PartitionRange.java
> +    public boolean isInteract(PartitionRange o) {
Can I fix it in the later pr?: https://github.com/StarRocks/starrocks/pull/26982

2023-07-12 16:18 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 58 / 60 (96.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/common/PartitionRange.java|17|19|89.47%|[75, 78]|
|:large_blue_circle:|com/starrocks/sql/common/SyncPartitionUtils.java|41|41|100.00%|[]|

2023-07-13 01:59 UTC, mofeiatwork approved these changes

2023-07-13 03:30 UTC, ABingHuang approved these changes

2023-07-13 05:10 UTC, merged

2023-07-13 05:10 UTC, wanpengfei-git commented
@Mergifyio backport branch-3.1