Check and resolve conflict in RowsetUpdateStates::apply
StarRocks/starrocks pull request #2795
Opened 2022-01-12 02:47 UTC by sevev

check and resolve conflict in RowsetUpdateStates::apply if conflict exists
1. if the row has been upsert, re-read this row's value
2. if the row has been deleted, set this row's value to its default value

2022-01-13 03:03 UTC, chaoyli approved these changes

2022-01-13 11:06 UTC, decster requested changes

2022-01-13 11:06 UTC, decster commented on be/src/storage/rowset_update_state.cpp
> +        }
Only create this when there is conflict

2022-01-13 11:06 UTC, decster commented on be/src/storage/rowset_update_state.cpp
> +                                                                 &_partial_update_states[i].write_columns));
the number of conflicts is usually very small, could we avoid copying the entire column? just set the rows that need to be updated.

2022-01-13 11:06 UTC, decster commented on be/src/storage/rowset_update_state.cpp
> +            "check partial rowset conflict tablet:$0 rowset:$1 #column:$2 getrowid:$3ms #resolve_conflict $4ms",
also log number of conflict/updated rows rows

2022-01-13 11:06 UTC, decster commented on be/src/storage/rowset_update_state.cpp
> +Status RowsetUpdateState::_check_conflict(Tablet* tablet, Rowset* rowset, uint32_t rowset_id,
this method not only check conflict, but also resolve the conflict, so maybe change to _check_and_resolve_conflict ?

2022-01-18 13:36 UTC, sevev commented
duplicate of https://github.com/StarRocks/starrocks/pull/2919

2022-01-18 13:36 UTC, closed without merging