[BugFix]Do not rewrite after update unrelated basetable's partitions
StarRocks/starrocks pull request #28907
Opened 2023-08-09 02:38 UTC by hongli-my

Fixes #28799

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

2023-08-09 09:51 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|2|2|100.00%|[]|

2023-08-10 07:17 UTC, ABingHuang requested changes

2023-08-10 07:17 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
> +            partitionNames.retainAll(mvPartitionsNames);
partitionNames is the changed partitions of base table, but mvPartitionsNames is the partition names of mv.
I think we can not decide the relationship between them

2023-08-10 07:36 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java
> +            partitionNames.retainAll(mvPartitionsNames);
I think you should consider a.id_date = b.id2_date

2024-12-01 10:39 UTC, closed without merging