Proper error handling for CompactionState::load.
StarRocks/starrocks pull request #2909
Opened 2022-01-18 07:22 UTC by Linkerist

resolve #2804

2022-01-18 08:15 UTC, decster requested changes

2022-01-18 08:15 UTC, decster commented on be/src/storage/tablet_updates.cpp
> +        LOG(ERROR) << msg;
WARNING

2022-01-20 02:06 UTC, decster approved these changes

2022-01-20 05:01 UTC, chaoyli approved these changes

2022-01-20 05:01 UTC, merged