[WIP] Support where exprs in synchronized materialized view
StarRocks/starrocks pull request #31905
Opened 2023-09-27 10:11 UTC by LiShuMing

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

2023-09-28 03:36 UTC, wanpengfei-git commented
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 89 / 197 (45.18%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.cpp|0|21|00.00%|[40, 424, 425, 426, 430, 432, 435, 438, 517, 519, 520, 521, 522, 524, 525, 527, 528, 529, 531, 532, 536]|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.h|0|2|00.00%|[246, 252]|
|:large_blue_circle:|src/storage/rowset/rowset_writer.cpp|0|1|00.00%|[886]|
|:large_blue_circle:|src/exec/tablet_sink.cpp|0|4|00.00%|[149, 188, 189, 330]|
|:large_blue_circle:|src/storage/schema_change_utils.h|1|5|20.00%|[45, 47, 49, 67]|
|:large_blue_circle:|src/storage/schema_change_utils.cpp|52|120|43.33%|[213, 216, 217, 218, 220, 221, 222, 225, 226, 241, 242, 243, 246, 247, 248, 250, 268, 269, 270, 281, 297, 298, 299, 300, 310, 312, 313, 314, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 341, 343, 344, 345, 348, 349, 355, 356, 357, 422, 431, 432, 433, 438, 439, 530, 609, 610]|
|:large_blue_circle:|src/storage/schema_change.cpp|27|35|77.14%|[429, 444, 445, 451, 452, 453, 549, 703]|
|:large_blue_circle:|src/storage/lake/schema_change.cpp|6|6|100.00%|[]|
|:large_blue_circle:|src/exec/tablet_info.cpp|3|3|100.00%|[]|

2023-09-28 03:36 UTC, wanpengfei-git commented
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 119 / 176 (67.61%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|1|41|02.44%|[306, 308, 309, 310, 311, 314, 315, 316, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 353, 354, 356, 357]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MVUtils.java|1|2|50.00%|[97]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|6|66.67%|[249, 270]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|6|8|75.00%|[219, 332]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|56|65|86.15%|[370, 373, 523, 524, 526, 527, 528, 534, 985]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|45|48|93.75%|[221, 222, 252]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/InPredicate.java|3|3|100.00%|[]|

2023-09-28 04:01 UTC, wanpengfei-git commented
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 119 / 176 (67.61%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|1|41|02.44%|[306, 308, 309, 310, 311, 314, 315, 316, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 353, 354, 356, 357]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MVUtils.java|1|2|50.00%|[97]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|6|66.67%|[249, 270]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|6|8|75.00%|[219, 332]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|56|65|86.15%|[370, 373, 523, 524, 526, 527, 528, 534, 985]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|45|48|93.75%|[221, 222, 252]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/InPredicate.java|3|3|100.00%|[]|

2023-09-28 04:01 UTC, wanpengfei-git commented
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 91 / 199 (45.73%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.cpp|0|21|00.00%|[40, 424, 425, 426, 430, 432, 435, 438, 517, 519, 520, 521, 522, 524, 525, 527, 528, 529, 531, 532, 536]|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.h|0|2|00.00%|[246, 252]|
|:large_blue_circle:|src/storage/rowset/rowset_writer.cpp|0|1|00.00%|[886]|
|:large_blue_circle:|src/exec/tablet_sink.cpp|0|4|00.00%|[149, 188, 189, 330]|
|:large_blue_circle:|src/storage/schema_change_utils.h|1|5|20.00%|[45, 47, 49, 67]|
|:large_blue_circle:|src/storage/schema_change_utils.cpp|52|120|43.33%|[213, 216, 217, 218, 220, 221, 222, 225, 226, 241, 242, 243, 246, 247, 248, 250, 268, 269, 270, 281, 297, 298, 299, 300, 310, 312, 313, 314, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 341, 343, 344, 345, 348, 349, 355, 356, 357, 422, 431, 432, 433, 438, 439, 530, 609, 610]|
|:large_blue_circle:|src/storage/schema_change.cpp|29|37|78.38%|[429, 444, 445, 451, 452, 453, 549, 703]|
|:large_blue_circle:|src/storage/lake/schema_change.cpp|6|6|100.00%|[]|
|:large_blue_circle:|src/exec/tablet_info.cpp|3|3|100.00%|[]|

2023-09-28 04:30 UTC, wanpengfei-git commented
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 119 / 176 (67.61%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|1|41|02.44%|[306, 308, 309, 310, 311, 314, 315, 316, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 353, 354, 356, 357]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MVUtils.java|1|2|50.00%|[97]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|6|66.67%|[249, 270]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|6|8|75.00%|[219, 332]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|56|65|86.15%|[370, 373, 523, 524, 526, 527, 528, 534, 985]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|45|48|93.75%|[221, 222, 252]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/InPredicate.java|3|3|100.00%|[]|

2023-09-28 04:30 UTC, wanpengfei-git commented
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 91 / 199 (45.73%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.cpp|0|21|00.00%|[40, 424, 425, 426, 430, 432, 435, 438, 517, 519, 520, 521, 522, 524, 525, 527, 528, 529, 531, 532, 536]|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.h|0|2|00.00%|[246, 252]|
|:large_blue_circle:|src/storage/rowset/rowset_writer.cpp|0|1|00.00%|[886]|
|:large_blue_circle:|src/exec/tablet_sink.cpp|0|4|00.00%|[149, 188, 189, 330]|
|:large_blue_circle:|src/storage/schema_change_utils.h|1|5|20.00%|[45, 47, 49, 67]|
|:large_blue_circle:|src/storage/schema_change_utils.cpp|52|120|43.33%|[213, 216, 217, 218, 220, 221, 222, 225, 226, 241, 242, 243, 246, 247, 248, 250, 268, 269, 270, 281, 297, 298, 299, 300, 310, 312, 313, 314, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 341, 343, 344, 345, 348, 349, 355, 356, 357, 422, 431, 432, 433, 438, 439, 530, 609, 610]|
|:large_blue_circle:|src/storage/schema_change.cpp|29|37|78.38%|[429, 444, 445, 451, 452, 453, 549, 703]|
|:large_blue_circle:|src/storage/lake/schema_change.cpp|6|6|100.00%|[]|
|:large_blue_circle:|src/exec/tablet_info.cpp|3|3|100.00%|[]|

2023-10-02 00:59 UTC, wanpengfei-git commented
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 119 / 176 (67.61%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|1|41|02.44%|[306, 308, 309, 310, 311, 314, 315, 316, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 353, 354, 356, 357]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MVUtils.java|1|2|50.00%|[97]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|6|66.67%|[249, 270]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|6|8|75.00%|[219, 332]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|56|65|86.15%|[370, 373, 523, 524, 526, 527, 528, 534, 985]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|45|48|93.75%|[221, 222, 252]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/InPredicate.java|3|3|100.00%|[]|

2023-10-02 00:59 UTC, wanpengfei-git commented
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 92 / 201 (45.77%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.cpp|0|21|00.00%|[40, 424, 425, 426, 430, 432, 435, 438, 517, 519, 520, 521, 522, 524, 525, 527, 528, 529, 531, 532, 536]|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.h|0|2|00.00%|[246, 252]|
|:large_blue_circle:|src/storage/rowset/rowset_writer.cpp|0|1|00.00%|[886]|
|:large_blue_circle:|src/exec/tablet_sink.cpp|0|4|00.00%|[149, 188, 189, 330]|
|:large_blue_circle:|src/storage/schema_change_utils.h|1|5|20.00%|[45, 47, 49, 67]|
|:large_blue_circle:|src/storage/schema_change_utils.cpp|53|122|43.44%|[217, 218, 219, 220, 221, 222, 225, 226, 234, 246, 247, 248, 250, 270, 272, 273, 285, 286, 297, 298, 299, 300, 310, 312, 313, 314, 318, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 341, 343, 344, 345, 348, 349, 355, 356, 357, 367, 422, 431, 432, 433, 438, 439, 440, 458, 530, 610, 613, 614]|
|:large_blue_circle:|src/storage/schema_change.cpp|29|37|78.38%|[429, 444, 445, 451, 452, 453, 549, 703]|
|:large_blue_circle:|src/storage/lake/schema_change.cpp|6|6|100.00%|[]|
|:large_blue_circle:|src/exec/tablet_info.cpp|3|3|100.00%|[]|

2023-10-04 01:26 UTC, wanpengfei-git commented
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 119 / 176 (67.61%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|1|41|02.44%|[306, 308, 309, 310, 311, 314, 315, 316, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 353, 354, 356, 357]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MVUtils.java|1|2|50.00%|[97]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|6|66.67%|[249, 270]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|6|8|75.00%|[219, 332]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|56|65|86.15%|[370, 373, 523, 524, 526, 527, 528, 534, 985]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|45|48|93.75%|[221, 222, 252]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/InPredicate.java|3|3|100.00%|[]|

2023-10-04 03:06 UTC, wanpengfei-git commented
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 92 / 201 (45.77%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.cpp|0|21|00.00%|[40, 424, 425, 426, 430, 432, 435, 438, 517, 519, 520, 521, 522, 524, 525, 527, 528, 529, 531, 532, 536]|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.h|0|2|00.00%|[246, 252]|
|:large_blue_circle:|src/storage/rowset/rowset_writer.cpp|0|1|00.00%|[886]|
|:large_blue_circle:|src/exec/tablet_sink.cpp|0|4|00.00%|[149, 188, 189, 330]|
|:large_blue_circle:|src/storage/schema_change_utils.h|1|5|20.00%|[45, 47, 49, 67]|
|:large_blue_circle:|src/storage/schema_change_utils.cpp|53|122|43.44%|[217, 218, 219, 220, 221, 222, 225, 226, 234, 246, 247, 248, 250, 270, 272, 273, 285, 286, 297, 298, 299, 300, 310, 312, 313, 314, 318, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 341, 343, 344, 345, 348, 349, 355, 356, 357, 367, 422, 431, 432, 433, 438, 439, 440, 458, 530, 610, 613, 614]|
|:large_blue_circle:|src/storage/schema_change.cpp|29|37|78.38%|[429, 444, 445, 451, 452, 453, 549, 703]|
|:large_blue_circle:|src/storage/lake/schema_change.cpp|6|6|100.00%|[]|
|:large_blue_circle:|src/exec/tablet_info.cpp|3|3|100.00%|[]|

2023-10-16 08:07 UTC, wanpengfei-git commented
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 119 / 176 (67.61%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|1|41|02.44%|[317, 319, 320, 321, 322, 325, 326, 327, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 364, 365, 367, 368]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MVUtils.java|1|2|50.00%|[97]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|6|66.67%|[275, 296]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|6|8|75.00%|[219, 332]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|56|65|86.15%|[371, 374, 524, 525, 527, 528, 529, 535, 986]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|45|48|93.75%|[221, 222, 252]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/InPredicate.java|3|3|100.00%|[]|

2023-10-16 08:10 UTC, wanpengfei-git commented
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 81 / 159 (50.94%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.cpp|0|21|00.00%|[40, 424, 425, 426, 430, 432, 435, 438, 517, 519, 520, 521, 522, 524, 525, 527, 528, 529, 531, 532, 536]|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.h|0|2|00.00%|[246, 252]|
|:large_blue_circle:|src/exec/tablet_info.cpp|0|3|00.00%|[144, 145, 146]|
|:large_blue_circle:|src/storage/rowset/rowset_writer.cpp|0|1|00.00%|[889]|
|:large_blue_circle:|src/exec/tablet_sink.cpp|0|4|00.00%|[149, 188, 189, 330]|
|:large_blue_circle:|src/storage/schema_change_utils.h|1|5|20.00%|[45, 47, 49, 67]|
|:large_blue_circle:|src/storage/schema_change_utils.cpp|49|86|56.98%|[217, 218, 219, 220, 221, 222, 225, 226, 234, 246, 247, 248, 250, 265, 277, 284, 286, 287, 290, 297, 298, 299, 300, 344, 391, 393, 394, 395, 396, 397, 400, 401, 402, 404, 499, 500, 501]|
|:large_blue_circle:|src/storage/schema_change.cpp|25|31|80.65%|[429, 446, 453, 457, 699, 700]|
|:large_blue_circle:|src/storage/lake/schema_change.cpp|6|6|100.00%|[]|

2023-10-16 10:20 UTC, wanpengfei-git commented
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 119 / 176 (67.61%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|1|41|02.44%|[317, 319, 320, 321, 322, 325, 326, 327, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 364, 365, 367, 368]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MVUtils.java|1|2|50.00%|[97]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|6|66.67%|[275, 296]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|6|8|75.00%|[219, 332]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|56|65|86.15%|[371, 374, 524, 525, 527, 528, 529, 535, 986]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|45|48|93.75%|[221, 222, 252]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/InPredicate.java|3|3|100.00%|[]|

2023-10-16 10:21 UTC, wanpengfei-git commented
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 71 / 168 (42.26%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.cpp|0|21|00.00%|[40, 424, 425, 426, 430, 432, 435, 438, 517, 519, 520, 521, 522, 524, 525, 527, 528, 529, 531, 532, 536]|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.h|0|2|00.00%|[246, 252]|
|:large_blue_circle:|src/exec/tablet_info.cpp|0|3|00.00%|[144, 145, 146]|
|:large_blue_circle:|src/storage/rowset/rowset_writer.cpp|0|1|00.00%|[889]|
|:large_blue_circle:|src/exec/tablet_sink.cpp|0|4|00.00%|[149, 188, 189, 330]|
|:large_blue_circle:|src/storage/schema_change_utils.h|1|5|20.00%|[45, 47, 49, 67]|
|:large_blue_circle:|src/storage/schema_change_utils.cpp|39|95|41.05%|[216, 217, 219, 220, 221, 222, 225, 236, 238, 239, 240, 241, 242, 243, 246, 247, 268, 275, 277, 278, 279, 280, 281, 283, 284, 285, 286, 287, 290, 297, 298, 300, 310, 312, 313, 367, 368, 369, 370, 373, 374, 375, 376, 377, 380, 381, 389, 390, 391, 393, 467, 468, 470, 646, 647, 648]|
|:large_blue_circle:|src/storage/schema_change.cpp|25|31|80.65%|[429, 446, 453, 457, 699, 700]|
|:large_blue_circle:|src/storage/lake/schema_change.cpp|6|6|100.00%|[]|

2023-10-17 04:40 UTC, wanpengfei-git commented
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 119 / 176 (67.61%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|1|41|02.44%|[317, 319, 320, 321, 322, 325, 326, 327, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 364, 365, 367, 368]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MVUtils.java|1|2|50.00%|[97]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|6|66.67%|[275, 296]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|6|8|75.00%|[219, 332]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|56|65|86.15%|[371, 374, 524, 525, 527, 528, 529, 535, 986]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|45|48|93.75%|[221, 222, 252]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/InPredicate.java|3|3|100.00%|[]|

2023-10-17 04:40 UTC, wanpengfei-git commented
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 97 / 246 (39.43%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.cpp|0|33|00.00%|[39, 40, 424, 425, 426, 427, 428, 431, 432, 433, 434, 435, 436, 437, 516, 518, 520, 522, 523, 524, 525, 526, 529, 530, 531, 534, 910, 911, 912, 927, 942, 943, 944]|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.h|0|2|00.00%|[251, 252]|
|:large_blue_circle:|src/exec/tablet_sink.cpp|0|3|00.00%|[149, 188, 330]|
|:large_blue_circle:|src/storage/schema_change_utils.h|1|12|08.33%|[67, 68, 69, 70, 71, 72, 99, 100, 101, 102, 103]|
|:large_blue_circle:|src/storage/schema_change_utils.cpp|51|142|35.92%|[215, 216, 217, 219, 220, 221, 222, 223, 225, 237, 238, 239, 240, 241, 242, 245, 246, 247, 256, 259, 260, 261, 263, 264, 265, 266, 267, 271, 272, 273, 275, 276, 292, 297, 306, 312, 313, 314, 319, 320, 321, 322, 323, 324, 325, 326, 329, 330, 331, 332, 333, 334, 335, 336, 338, 339, 342, 343, 345, 397, 398, 399, 400, 401, 402, 403, 405, 407, 410, 411, 412, 413, 415, 416, 417, 419, 420, 421, 422, 435, 506, 507, 508, 511, 512, 515, 516, 518, 523, 614, 700]|
|:large_blue_circle:|src/exec/tablet_info.cpp|2|3|66.67%|[145]|
|:large_blue_circle:|src/storage/rowset/rowset_writer.cpp|2|3|66.67%|[888]|
|:large_blue_circle:|src/storage/schema_change.cpp|34|41|82.93%|[527, 717, 719, 720, 722, 778, 781]|
|:large_blue_circle:|src/storage/lake/schema_change.cpp|7|7|100.00%|[]|

2023-10-17 06:53 UTC, wanpengfei-git commented
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 119 / 176 (67.61%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|1|41|02.44%|[317, 319, 320, 321, 322, 325, 326, 327, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 364, 365, 367, 368]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MVUtils.java|1|2|50.00%|[97]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|6|66.67%|[275, 296]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|6|8|75.00%|[219, 332]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|56|65|86.15%|[371, 374, 524, 525, 527, 528, 529, 535, 986]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|45|48|93.75%|[221, 222, 252]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/InPredicate.java|3|3|100.00%|[]|

2023-10-17 06:54 UTC, wanpengfei-git commented
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 98 / 247 (39.68%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.cpp|0|33|00.00%|[39, 40, 424, 425, 426, 427, 428, 431, 432, 433, 434, 435, 436, 437, 516, 518, 520, 522, 523, 524, 525, 526, 529, 530, 531, 534, 910, 911, 912, 927, 942, 943, 944]|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.h|0|2|00.00%|[251, 252]|
|:large_blue_circle:|src/exec/tablet_sink.cpp|0|3|00.00%|[149, 188, 330]|
|:large_blue_circle:|src/storage/schema_change_utils.h|1|12|08.33%|[67, 68, 69, 70, 71, 72, 99, 100, 101, 102, 103]|
|:large_blue_circle:|src/storage/schema_change_utils.cpp|51|142|35.92%|[215, 216, 217, 219, 220, 221, 222, 223, 225, 237, 238, 239, 240, 241, 242, 245, 246, 247, 256, 259, 260, 261, 263, 264, 265, 266, 267, 271, 272, 273, 275, 276, 292, 297, 306, 312, 313, 314, 319, 320, 321, 322, 323, 324, 325, 326, 329, 330, 331, 332, 333, 334, 335, 336, 338, 339, 342, 343, 345, 397, 398, 399, 400, 401, 402, 403, 405, 407, 410, 411, 412, 413, 415, 416, 417, 419, 420, 421, 422, 435, 506, 507, 508, 511, 512, 515, 516, 518, 523, 614, 700]|
|:large_blue_circle:|src/exec/tablet_info.cpp|2|3|66.67%|[145]|
|:large_blue_circle:|src/storage/rowset/rowset_writer.cpp|2|3|66.67%|[888]|
|:large_blue_circle:|src/storage/schema_change.cpp|34|41|82.93%|[527, 717, 719, 720, 722, 778, 781]|
|:large_blue_circle:|src/storage/lake/schema_change.cpp|7|7|100.00%|[]|
|:large_blue_circle:|src/storage/rowset_merger.cpp|1|1|100.00%|[]|

2023-10-17 12:05 UTC, wanpengfei-git commented
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 127 / 176 (72.16%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|1|41|02.44%|[317, 319, 320, 321, 322, 325, 326, 327, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 364, 365, 367, 368]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|6|66.67%|[275, 296]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|7|8|87.50%|[219]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|61|65|93.85%|[371, 374, 535, 986]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|46|48|95.83%|[221, 222]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MVUtils.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/InPredicate.java|3|3|100.00%|[]|

2023-10-17 12:06 UTC, wanpengfei-git commented
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 97 / 246 (39.43%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.cpp|0|33|00.00%|[39, 40, 424, 425, 426, 427, 428, 431, 432, 433, 434, 435, 436, 437, 516, 518, 520, 522, 523, 524, 525, 526, 529, 530, 531, 534, 910, 911, 912, 927, 942, 943, 944]|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.h|0|2|00.00%|[251, 252]|
|:large_blue_circle:|src/exec/tablet_sink.cpp|0|3|00.00%|[149, 188, 330]|
|:large_blue_circle:|src/storage/schema_change_utils.h|1|12|08.33%|[67, 68, 69, 70, 71, 72, 99, 100, 101, 102, 103]|
|:large_blue_circle:|src/storage/schema_change_utils.cpp|51|142|35.92%|[215, 216, 217, 219, 220, 221, 222, 223, 225, 237, 238, 239, 240, 241, 242, 245, 246, 247, 256, 259, 260, 261, 263, 264, 265, 266, 267, 271, 272, 273, 275, 276, 292, 297, 306, 312, 313, 314, 319, 320, 321, 322, 323, 324, 325, 326, 329, 330, 331, 332, 333, 334, 335, 336, 338, 339, 342, 343, 345, 397, 398, 399, 400, 401, 402, 403, 405, 407, 410, 411, 412, 413, 415, 416, 417, 419, 420, 421, 422, 435, 506, 507, 508, 511, 512, 515, 516, 518, 523, 614, 700]|
|:large_blue_circle:|src/exec/tablet_info.cpp|2|3|66.67%|[145]|
|:large_blue_circle:|src/storage/rowset/rowset_writer.cpp|2|3|66.67%|[888]|
|:large_blue_circle:|src/storage/schema_change.cpp|34|41|82.93%|[527, 717, 719, 720, 722, 778, 781]|
|:large_blue_circle:|src/storage/lake/schema_change.cpp|7|7|100.00%|[]|

2023-10-17 14:06 UTC, wanpengfei-git commented
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 127 / 176 (72.16%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|1|41|02.44%|[317, 319, 320, 321, 322, 325, 326, 327, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 364, 365, 367, 368]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|6|66.67%|[275, 296]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|7|8|87.50%|[219]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|61|65|93.85%|[371, 374, 535, 986]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|46|48|95.83%|[221, 222]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MVUtils.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/InPredicate.java|3|3|100.00%|[]|

2023-10-17 14:07 UTC, wanpengfei-git commented
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 97 / 246 (39.43%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.cpp|0|33|00.00%|[39, 40, 424, 425, 426, 427, 428, 431, 432, 433, 434, 435, 436, 437, 516, 518, 520, 522, 523, 524, 525, 526, 529, 530, 531, 534, 910, 911, 912, 927, 942, 943, 944]|
|:large_blue_circle:|src/exec/tablet_sink_index_channel.h|0|2|00.00%|[251, 252]|
|:large_blue_circle:|src/exec/tablet_sink.cpp|0|3|00.00%|[149, 188, 330]|
|:large_blue_circle:|src/storage/schema_change_utils.h|1|12|08.33%|[67, 68, 69, 70, 71, 72, 99, 100, 101, 102, 103]|
|:large_blue_circle:|src/storage/schema_change_utils.cpp|51|142|35.92%|[215, 216, 217, 219, 220, 221, 222, 223, 225, 237, 238, 239, 240, 241, 242, 245, 246, 247, 256, 259, 260, 261, 263, 264, 265, 266, 267, 271, 272, 273, 275, 276, 292, 297, 306, 312, 313, 314, 319, 320, 321, 322, 323, 324, 325, 326, 329, 330, 331, 332, 333, 334, 335, 336, 338, 339, 342, 343, 345, 397, 398, 399, 400, 401, 402, 403, 405, 407, 410, 411, 412, 413, 415, 416, 417, 419, 420, 421, 422, 435, 506, 507, 508, 511, 512, 515, 516, 518, 523, 614, 700]|
|:large_blue_circle:|src/exec/tablet_info.cpp|2|3|66.67%|[145]|
|:large_blue_circle:|src/storage/rowset/rowset_writer.cpp|2|3|66.67%|[888]|
|:large_blue_circle:|src/storage/schema_change.cpp|34|41|82.93%|[527, 717, 719, 720, 722, 778, 781]|
|:large_blue_circle:|src/storage/lake/schema_change.cpp|7|7|100.00%|[]|

2023-11-01 08:54 UTC, satanson approved these changes, later dismissed

2023-11-02 07:27 UTC, ABingHuang requested changes

2023-11-02 07:27 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedIndexMeta.java
> +    private Expr whereClause;
it seems that you push whereClause in columnNameToDefineExpr?

2023-11-02 07:27 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedIndexMeta.java
> +    private Expr whereClause;
how do we serialize Expr?

2023-11-02 07:27 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedIndexMeta.java
> +    private Expr whereClause;
do we support all types of exprs? tests covered?

2023-11-02 07:27 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
> +                LOG.info("OlapTableSink Where clause: {}", whereClause.explain());
is it necessary?

2023-11-02 07:27 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/planner/OlapTableSink.java
> +
remove extra empty line

2023-11-03 02:13 UTC, LiShuMing commented on fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedIndexMeta.java
> +    private Expr whereClause;
> do you test refresh fe? I think we should persist this field into meta?
> it seems that you push whereClause in columnNameToDefineExpr?

Yep. Just like original `definedExpr` for each column, save `whereExpr` into `WHERE_PREDICATE_COLUMN_NAME` as a special `definedExpr` which is derived from  `parseDefineExprWithoutAnalyze`. This routine is just the same with `definedExpr`.

> do we support all types of exprs? tests covered?

I just tested some exprs in sql-tester. But I think just like the normal expression if the input slot refs are enough, we can just use the be's expression evaluation framework to eval the where expression?

2023-11-03 02:23 UTC, LiShuMing commented on fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedIndexMeta.java
> +        return indexMeta.whereClause == this.whereClause;
fixed.

2023-11-03 06:14 UTC, ABingHuang approved these changes

2023-11-03 06:38 UTC, satanson approved these changes

2023-11-03 07:08 UTC, srlch approved these changes

2023-11-06 07:28 UTC, kangkaisen approved these changes

2023-11-06 07:32 UTC, merged