Enhanced materialized view of single column with multiple aggregate functions, Fixes #3207
StarRocks/starrocks pull request #3208
Opened 2022-01-31 10:33 UTC by winbillatgithub

## What type of PR is this：
- [ ] bug
- [ ] feature
- [✓] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #3207 

## Problem Summary(Required) ：
- As of now, the mv only supports one column with only one aggregate function.
- This needs to be enhanced, like the following mv:
`
create materialized view enhanced_mv as 
select name, sum(height),max(height),min(height),sum(weight),max(weight) from student group by name
`

2022-01-31 10:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StarRocks/starrocks?pullRequest=3208) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/StarRocks/starrocks?pullRequest=3208) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StarRocks/starrocks?pullRequest=3208) it.</sub>

2022-02-08 01:28 UTC, chaoyli commented
@winbillatgithub Thanks for your contribution. The unit test of FE can not be passed. You can use the following command to run the unit test.
```
sh run-fe-ut.sh --run
```
<img width="651" alt="image" src="https://user-images.githubusercontent.com/44767902/152900508-178b7884-8e76-40c3-915d-2e5ad8b6a694.png">

2022-02-08 06:26 UTC, winbillatgithub commented
> 

@chaoyli Hi, the basic logic is to identify a column with name + aggregate function, there's some differences from the previous design.  If the unit tests of FE want to be passed, the failed unit test cases need to be modified with my logic. 
Before making any changes, I'd like to discuss my design first and my wechat id : antispy 
thanks.

2022-02-10 09:01 UTC, DeepThinker666 requested changes

2022-02-10 09:02 UTC, DeepThinker666 commented
IMO, In be, we should not use column + "#" + agg name as column name, we should use column id to find column.

2023-02-16 02:21 UTC, closed without merging