Implement MutableIndex basic operations
StarRocks/starrocks pull request #3224
Opened 2022-02-08 03:06 UTC by decster

## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] others

## Which issues of this PR fixes ：

Fixes #3223

## Problem Summary(Required) ：
Implement MutableIndex basic operations: get, upsert, insert, erase

2022-02-08 04:37 UTC, decster commented
run starrocks_clang-format

2022-02-09 13:42 UTC, chaoyli requested changes

2022-02-10 03:25 UTC, chaoyli approved these changes

2022-02-10 11:43 UTC, sevev approved these changes

2022-02-10 12:00 UTC, Astralidea approved these changes

2022-02-10 12:00 UTC, merged