[WIP]delete supports partition prune
StarRocks/starrocks pull request #3253
Opened 2022-02-09 06:38 UTC by Astralidea

## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #3137

## Problem Summary(Required) ：

This is implemented using the old optimizer, which may not be perfect when prune. A better way should be to use the new optimizer, but the implementation may be more complicated.

2022-02-14 12:27 UTC, wyb commented on fe/fe-core/src/main/java/com/starrocks/load/DeleteHandler.java
> +            } else if (condition instanceof InPredicate) {
Should check and filter `not in predicate`.

2022-02-14 12:27 UTC, wyb commented on fe/fe-core/src/main/java/com/starrocks/load/DeleteHandler.java
> +            }
Build the map outside of the for loop.

2022-02-14 12:27 UTC, wyb commented on fe/fe-core/src/main/java/com/starrocks/load/DeleteHandler.java
> +                            }
```
for (Long partitionId : selectedPartitionIds) {
    Partition partition = olapTable.getPartition(partitionId);
    partitionNames.add(partition.getName());
}
```

2022-02-18 08:11 UTC, wyb approved these changes, later dismissed

2022-02-18 09:57 UTC, chaoyli requested changes

2022-02-18 09:57 UTC, chaoyli commented on fe/fe-core/src/test/java/com/starrocks/load/DeletePruneTest.java
> +package com.starrocks.load;
Add license in the header.

2022-02-18 09:57 UTC, chaoyli commented on fe/fe-core/src/main/java/com/starrocks/load/DeleteHandler.java
> +                        break;
Does not filter.upperBoundInclusive?

2022-02-18 10:43 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/load/DeleteHandler.java
> +                        filter.lowerBoundInclusive = true;
This just copy ColumnFilterConverter.java 107~130. in fact lowerBoundInclusive may not be set.

2022-02-23 13:35 UTC, chaoyli approved these changes

2022-02-28 03:15 UTC, Seaven approved these changes

2022-02-28 13:09 UTC, merged