Add limit to reduce the input rowsets for base compaction.
StarRocks/starrocks pull request #3466
Opened 2022-02-17 09:27 UTC by Linkerist

## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #3432 

## Problem Summary(Required) ：

Add configuration for base compaction, when get enough segments, do not pick more input rowsets from candidate rowsets.

2022-02-17 09:41 UTC, chaoyli commented on be/src/storage/vectorized/base_compaction.cpp
> +    for (auto rowset : candidate_rowsets) {
auto& rowset

2022-02-17 09:43 UTC, chaoyli requested changes

2022-02-17 09:43 UTC, chaoyli commented on be/src/storage/vectorized/base_compaction.cpp
>      if (_input_rowsets.size() > config::base_compaction_num_cumulative_deltas) {
config::base_compaction_num_cumulative_deltas is redundant

2022-02-17 13:13 UTC, chaoyli commented on be/src/common/config.h
> +CONF_mInt64(max_base_compaction_num_singleton_deltas, "1000");
The default limit of base compaction is lower better. 100 is ok.

2022-02-17 13:30 UTC, chaoyli approved these changes

2022-02-17 13:33 UTC, trueeyu commented on be/src/common/config.h
> +CONF_mInt64(max_base_compaction_num_singleton_deltas, "100");
The default value is too large

2022-02-17 13:34 UTC, trueeyu commented on be/src/common/config.h
> +CONF_mInt64(min_base_compaction_num_singleton_deltas, "5");
if one user has set base_compaction_num_cumulative_deltas, be will start fail

2022-02-23 02:51 UTC, trueeyu approved these changes

2022-02-23 02:55 UTC, Linkerist commented
run starrocks_clang-format

2022-02-23 03:14 UTC, Linkerist commented
run starrocks_be_unittest

2022-02-23 05:44 UTC, merged