fix a bug in compaction_manager
StarRocks/starrocks pull request #4290
Opened 2022-03-21 07:09 UTC by xiaoyong-z

Signed-off-by: xyz <a997647204@gmail.com>

## What type of PR is this：
- [ ☑️] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：
_data_dir_to_base_task_num_map uses the wrong comparison condition (previously config::cumulative_compaction_num_threads_per_disk), it should be config::base_compaction_num_threads_per_disk

2022-03-21 10:39 UTC, meegoo requested changes
1. use `- [x] bug` to mark list
2. commit message should be meaningful

2022-03-21 14:01 UTC, imay approved these changes, later dismissed

2022-03-22 07:11 UTC, meegoo approved these changes, later dismissed

2022-03-22 07:22 UTC, ABingHuang commented on be/src/storage/compaction_manager.cpp
> +                         << config::base_compaction_num_threads_per_disk;
change the log in line 110 to 
register compaction task failed for disk's running base tasks reach limit

2022-03-24 04:34 UTC, meegoo approved these changes

2022-03-24 06:04 UTC, imay approved these changes

2022-03-24 06:04 UTC, merged