[Doc] [BugFix] Add more docs about sync/async materialized views
StarRocks/starrocks pull request #43840
Opened 2024-04-10 07:45 UTC by LiShuMing

## Why I'm doing:

## What I'm doing:

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

2024-04-10 08:38 UTC, ABingHuang commented on docs/zh/reference/System_variable.md
> +* Description: Whether to rewrite input query in optimizer's CRO phase even for queries with multi tables.
use chinese?

2024-04-10 08:38 UTC, ABingHuang commented on docs/zh/reference/System_variable.md
> +* Description: Whether to enable view based rewrite or not. If true, treat logical view as unified node to rewrite rather than inlining it to be better for rewrite.
use chinese

2024-04-10 08:38 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/common/Config.java
> +    public static boolean enable_materialized_view_text_based_rewrite = true;
why use a config not a SessionVariable?

2024-04-10 12:09 UTC, kangkaisen commented on docs/en/administration/management/FE_configuration.md
> +##### enable_materialized_view_text_based_rewrite
why this is a config ,not session variable?

2024-04-19 05:57 UTC, LiShuMing commented
@mergify rebase

2024-04-19 09:12 UTC, ABingHuang approved these changes

2024-04-19 09:13 UTC, ABingHuang requested changes

2024-04-19 09:13 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/common/Config.java
> +    public static boolean enable_materialized_view_text_based_rewrite = true;
then session variable is enough? In which case we should use config other than session variable of enable_materialized_view_text_match_rewrite?

2024-04-19 09:17 UTC, kangkaisen approved these changes

2024-04-19 09:24 UTC, ABingHuang approved these changes

2024-04-19 10:09 UTC, merged