Fix rest of the problems of building on arm
StarRocks/starrocks pull request #452
Opened 2021-09-27 08:20 UTC by rickif

This PR is to solve the rest problems of buiding on aarch64, including following modifications:

1.new crc_hash functions adaption
2. hadoop for aarch64
3. OpenJDK for aarch64
4. correcting Apache Arrow 5.0.0 building option

2021-09-27 08:46 UTC, dirtysalt approved these changes, later dismissed

2021-09-27 08:47 UTC, dirtysalt commented
Thanks for this huge work of porting code to arm.

2021-09-27 08:47 UTC, Astralidea commented on thirdparty/vars.sh
> +HADOOP_AARCH64_DOWNLOAD="http://starrocks-thirdparty.oss-cn-zhangjiakou.aliyuncs.com/hadoop-3.3.0-aarch64.tar.gz"
Is it better to change this to CDN?

2021-09-27 15:19 UTC, imay approved these changes, later dismissed

2021-09-28 02:46 UTC, chaoyli approved these changes

2021-09-28 02:47 UTC, chaoyli approved these changes, later dismissed

2021-09-28 10:31 UTC, chaoyli requested changes

2021-09-28 10:31 UTC, chaoyli commented on thirdparty/vars-aarch64.sh
> +#!/bin/bash
use elastic license

2021-09-28 10:31 UTC, chaoyli commented on thirdparty/vars-x86_64.sh
> +#!/bin/bash
use elastic license

2021-09-28 10:58 UTC, rickif commented on thirdparty/vars-aarch64.sh
> +#!/bin/bash
Already changed to elastic license 2.0

2021-09-28 10:58 UTC, rickif commented on thirdparty/vars-x86_64.sh
> +#!/bin/bash
Already changed to elastic license 2.0

2021-09-28 15:21 UTC, imay approved these changes

2021-09-29 02:39 UTC, chaoyli approved these changes

2021-09-29 02:47 UTC, Astralidea approved these changes

2021-09-29 02:49 UTC, merged