[Enhancement] adjust MV's warehouse logic
StarRocks/starrocks pull request #45941
Opened 2024-05-20 11:58 UTC by starrocks-xupeng

## Why I'm doing:

## What I'm doing:

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

2024-05-20 17:38 UTC, mofeiatwork submitted a review, later dismissed

2024-05-21 03:00 UTC, yandongxiao requested changes

2024-05-21 03:00 UTC, yandongxiao commented on fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java
> -                }
I don't quite understand the working principle of MV. Why can this part of the logic be deleted?
If so, there will no such property in task created by MV.

2024-05-21 03:16 UTC, starrocks-xupeng commented on fe/fe-core/src/main/java/com/starrocks/scheduler/Task.java
> +    public String getWarehouseName() {
put it here to make code the same with enterprise version

2024-05-21 03:18 UTC, yandongxiao approved these changes

2024-05-21 03:40 UTC, mofeiatwork submitted a review, later dismissed

2024-05-21 09:36 UTC, kevincai approved these changes

2024-05-21 16:19 UTC, mofeiatwork approved these changes

2024-05-21 16:19 UTC, merged

2024-05-22 02:34 UTC, starrocks-xupeng commented
@mergify backport branch-3.2