Add compaction scheduler to storage engine
StarRocks/starrocks pull request #4598
Opened 2022-03-30 07:52 UTC by ABingHuang

## What type of PR is this：
- [ ] bug
- [X] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4592 

## Problem Summary(Required) ：

#3301 has add a event-based compaction framework. This is one of step of it. Compaction scheduler should be started in StorageEngine when config::enable_new_compaction_framework is true.

2022-03-31 11:51 UTC, decster approved these changes, later dismissed

2022-04-01 02:18 UTC, meegoo approved these changes, later dismissed

2022-04-01 06:27 UTC, chaoyli requested changes

2022-04-01 06:27 UTC, chaoyli commented on be/src/storage/olap_server.cpp
> +    if (!config::enable_new_compaction_framework) {
enable_event_based_compaction_framework

2022-04-01 08:51 UTC, chaoyli approved these changes

2022-04-01 09:44 UTC, decster approved these changes

2022-04-01 11:04 UTC, merged