Fix null partition value exception for hudi table
StarRocks/starrocks pull request #4599
Opened 2022-03-30 08:00 UTC by miomiocat

## What type of PR is this：
- [x] bug
- [x] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：
Bug:  
Closes #4568 

Feature:
Support clearing meta cache of hudi table on drop

## Problem Summary(Required) ：
`default` is used to represent NULL value of partition field for partition directory name in hudi instead of `__HIVE_DEFAULT_PARTITION__` in hive, so it is necessary to distinguish them.

2022-03-30 08:13 UTC, miomiocat commented
run starrocks_fe_unittest

2022-03-31 06:56 UTC, caneGuy requested changes

2022-03-31 06:56 UTC, caneGuy commented on fe/fe-core/src/main/java/com/starrocks/external/hive/HiveRepository.java
> +            LOG.warn("clean table {}.{} cache failed.", dbName, tableName,  e);
clean -> Clean

2022-03-31 06:56 UTC, caneGuy commented on fe/fe-core/src/main/java/com/starrocks/external/hive/HivePartitionKeysKey.java
> +    public boolean isHudiTable() {
This should be isHudiPartitionKey or isHudiPartition

2022-03-31 06:56 UTC, caneGuy commented on fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaCache.java
>              return partitionsCache.get(new HivePartitionKey(dbName, tableName, partitionValues, isHudiTable));
isHudiTable of HivePartitonKey should also rename to isHudiPartitionKey

2022-03-31 06:56 UTC, caneGuy commented on fe/fe-core/src/main/java/com/starrocks/external/HiveMetaStoreTableUtils.java
> +    public static Map<String, HiveColumnStats> getTableLevelColumnStats(String resourceName,
how about passing HMSTable object and remove isHudiTable for tracing?

2022-04-01 04:27 UTC, wanpengfei-git commented
#### [FE PR Coverage check]

:disappointed: **fail** : 65 / 146 (44.52%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/HiveRepository.java|0|20|00.00%|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|2|15|13.33%|
|:large_blue_circle:|com/starrocks/catalog/HudiTable.java|4|16|25.00%|
|:large_blue_circle:|com/starrocks/catalog/HiveTable.java|4|12|33.33%|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaCache.java|13|32|40.62%|
|:large_blue_circle:|com/starrocks/external/hive/HiveTableColumnsKey.java|5|8|62.50%|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaClient.java|4|6|66.67%|
|:large_blue_circle:|com/starrocks/external/hive/Utils.java|5|7|71.43%|
|:large_blue_circle:|com/starrocks/catalog/HiveMetaStoreTableInfo.java|14|16|87.50%|
|:large_blue_circle:|com/starrocks/external/hive/HivePartitionKeysKey.java|8|8|100.00%|
|:large_blue_circle:|com/starrocks/external/hive/HivePartitionKey.java|6|6|100.00%|

2022-04-01 04:37 UTC, dirtysalt submitted a review, later dismissed

2022-04-01 04:45 UTC, wanpengfei-git commented
#### [FE PR Coverage check]

:disappointed: **fail** : 65 / 146 (44.52%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/HiveRepository.java|0|20|00.00%|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|2|15|13.33%|
|:large_blue_circle:|com/starrocks/catalog/HudiTable.java|4|16|25.00%|
|:large_blue_circle:|com/starrocks/catalog/HiveTable.java|4|12|33.33%|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaCache.java|13|32|40.62%|
|:large_blue_circle:|com/starrocks/external/hive/HiveTableColumnsKey.java|5|8|62.50%|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaClient.java|4|6|66.67%|
|:large_blue_circle:|com/starrocks/external/hive/Utils.java|5|7|71.43%|
|:large_blue_circle:|com/starrocks/catalog/HiveMetaStoreTableInfo.java|14|16|87.50%|
|:large_blue_circle:|com/starrocks/external/hive/HivePartitionKeysKey.java|8|8|100.00%|
|:large_blue_circle:|com/starrocks/external/hive/HivePartitionKey.java|6|6|100.00%|

2022-04-01 08:36 UTC, caneGuy commented on fe/fe-core/src/main/java/com/starrocks/catalog/HudiTable.java
> +    public HiveMetaStoreTableInfo getHmsTableInfo() {
this should be thread-safe?

2022-04-01 08:49 UTC, caneGuy approved these changes

2022-04-01 08:58 UTC, dirtysalt approved these changes

2022-04-01 09:07 UTC, miomiocat commented
run starrocks_fe_unittest

2022-04-01 09:28 UTC, miomiocat commented
run starrocks_fe_unittest

2022-04-01 12:16 UTC, miomiocat commented
run starrocks_fe_unittest

2022-04-01 12:21 UTC, wanpengfei-git commented
#### [FE PR Coverage check]

:disappointed: **fail** : 67 / 150 (44.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/HiveRepository.java|0|20|00.00%|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|2|15|13.33%|
|:large_blue_circle:|com/starrocks/catalog/HudiTable.java|5|18|27.78%|
|:large_blue_circle:|com/starrocks/catalog/HiveTable.java|5|14|35.71%|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaCache.java|13|32|40.62%|
|:large_blue_circle:|com/starrocks/external/hive/HiveTableColumnsKey.java|5|8|62.50%|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaClient.java|4|6|66.67%|
|:large_blue_circle:|com/starrocks/external/hive/Utils.java|5|7|71.43%|
|:large_blue_circle:|com/starrocks/catalog/HiveMetaStoreTableInfo.java|14|16|87.50%|
|:large_blue_circle:|com/starrocks/external/hive/HivePartitionKeysKey.java|8|8|100.00%|
|:large_blue_circle:|com/starrocks/external/hive/HivePartitionKey.java|6|6|100.00%|

2022-04-01 12:42 UTC, merged

2022-04-01 12:46 UTC, miomiocat commented
@Mergifyio backport branch-2.2