docs(位图索引): 创建索引示例中添加表名
StarRocks/starrocks pull request #46547
Opened 2024-06-03 03:09 UTC by Xikl

## Why I'm doing:
文档示例不对
## What I'm doing:
修改文档位图索引实例，添加表名

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [x] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [x] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.3
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

2024-06-03 03:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StarRocks/starrocks?pullRequest=46547) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/StarRocks/starrocks?pullRequest=46547) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StarRocks/starrocks?pullRequest=46547) it.</sub>

2024-06-03 05:47 UTC, imay commented
@Xikl can you sign the CLA?

2024-06-28 06:01 UTC, Xikl commented
@imay please review it again

2024-10-25 16:03 UTC, DanRoscigno requested changes
Thanks @Xikl please see my change

2024-10-25 16:03 UTC, DanRoscigno commented on docs/zh/table_design/indexes/Bitmap_index.md
> +    CREATE INDEX lo_quantity_index (lo_quantity) ON lineorder_partial USING BITMAP;
@Xikl I believe this is the syntax:

```SQL
CREATE INDEX index_name ON table_name (column_name) USING BITMAP
```

So, the column name would be after the table name.

2024-10-25 16:03 UTC, DanRoscigno commented on docs/zh/table_design/indexes/Bitmap_index.md
> +    CREATE INDEX lo_quantity_index (lo_quantity) ON lineorder_partial USING BITMAP;
```suggestion
    CREATE INDEX lo_quantity_index ON lineorder_partial (lo_quantity) USING BITMAP;
```

2025-01-29 14:44 UTC, DanRoscigno approved these changes

2025-02-05 06:32 UTC, EsoragotoSpirit approved these changes

2025-02-05 06:32 UTC, merged