[Doc] Add docs for MV Default Resource Group
StarRocks/starrocks pull request #47695
Opened 2024-07-01 09:26 UTC by EsoragotoSpirit

Signed-off-by: EsoragotoSpirit <wanglichen@starrocks.com>

## Why I'm doing:

## What I'm doing:

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [x] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

2024-07-05 02:10 UTC, LiShuMing submitted a review, later dismissed

2024-07-05 10:04 UTC, DanRoscigno requested changes

2024-07-05 10:04 UTC, DanRoscigno commented on docs/en/administration/management/resource_management/resource_group.md
> +`default_wg` will be assigned to regular queries that are under the management of resource groups but doesn't match any classifier. The resource limits of `default_wg` are as follows:
```suggestion
`default_wg` will be assigned to regular queries that are under the management of resource groups but don't match any classifier. The resource limits of `default_wg` are as follows:
```

2024-07-05 10:16 UTC, DanRoscigno approved these changes, later dismissed

2024-07-08 02:18 UTC, wangsimo0 approved these changes

2024-07-08 02:20 UTC, yingtingdong approved these changes

2024-07-08 02:23 UTC, merged