[Doc] Add desc for BE config primary_key_limit_size
StarRocks/starrocks pull request #47832
Opened 2024-07-04 03:29 UTC by EsoragotoSpirit

## Why I'm doing:

## What I'm doing:

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [x] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

2024-07-04 03:36 UTC, yingtingdong submitted a review, later dismissed

2024-07-05 10:05 UTC, DanRoscigno requested changes

2024-07-05 10:05 UTC, DanRoscigno commented on docs/en/table_design/table_types/primary_key_table.md
> +- By default, the maximum length of a encoded primary key value is 128 bytes.
```suggestion
- By default, the maximum length of an encoded primary key value is 128 bytes.
```

2024-07-05 10:17 UTC, DanRoscigno approved these changes

2024-07-08 02:08 UTC, yingtingdong approved these changes

2024-07-08 02:08 UTC, merged