Discard memory check before doing checkpoint
StarRocks/starrocks pull request #4850
Opened 2022-04-06 12:40 UTC by gengjun-git

## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4849

## Problem Summary(Required) ：

Remove the memory check related code.

2022-04-06 13:30 UTC, wanpengfei-git commented
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

2022-04-11 13:17 UTC, chaoyli requested changes

2022-04-11 13:17 UTC, chaoyli commented on fe/fe-core/src/main/java/com/starrocks/common/Config.java
> -    /**
Please add commit message to describe the job.

2022-04-12 06:30 UTC, chaoyli approved these changes

2022-04-13 03:14 UTC, Astralidea approved these changes

2022-04-13 05:37 UTC, merged