Fix migration bug
StarRocks/starrocks pull request #4857
Opened 2022-04-07 05:06 UTC by ABingHuang

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4328

## Problem Summary(Required) ：

When clone tablet from path A to path B, and then back to path A, it will failed because the original tablet remains in path A. The original tablet is GCed async every one hour. Fix it by removing shutdown tablet when clone. And add ut to test this case.

2022-04-08 01:46 UTC, ABingHuang commented
run starrocks_fe_unittest

2022-04-08 11:50 UTC, chaoyli requested changes

2022-04-08 11:50 UTC, chaoyli commented on be/src/storage/task/engine_storage_migration_task.cpp
> +        // double check
Remove the code paths annotated.

2022-04-08 11:50 UTC, chaoyli commented on be/src/storage/task/engine_storage_migration_task.cpp
> +            Status st = StorageEngine::instance()->tablet_manager()->delete_shutdown_tablet(_tablet_id);
delete and remove should be unified into one word.

2022-04-08 11:50 UTC, chaoyli commented on be/src/storage/task/engine_storage_migration_task.cpp
> +            Status st = StorageEngine::instance()->tablet_manager()->delete_shutdown_tablet(_tablet_id);
delete and remove should be unified into one word.

2022-04-11 03:37 UTC, chaoyli approved these changes

2022-04-11 04:52 UTC, decster approved these changes

2022-04-11 06:24 UTC, merged