[WIP]Refresh framework for MaterializedView
StarRocks/starrocks pull request #5169
Opened 2022-04-16 09:45 UTC by Astralidea

## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4796

## Background
The old materialization attempts to only support a single table and do it in a synchronous refresh manner by mapping the partitions of the single table into a one-to-one mapping of the Base table and the MV table.

When the old materialized view is building a table, the process of creating the materialized view is asynchronous, but the asynchronous scheduling framework relies on the MasterDaemon to be inefficient.

In order to cope with the requirements of asynchronous refresh and asynchronous triggering of multi-table materialized views. Therefore, it is necessary to build a new refresh the framework.

## Scenario
This framework currently only focuses on asynchronous refreshes.
1.For real-time scenarios, users generally build multiple tables, and then periodically execute an SQL to refresh the target table.
2.For offline scenarios, the user will periodically refresh all of them once a day.

## Design
We mainly divide refresh scenarios into two categories, one is periodic refresh, and the other is due to table creation, Base table change (data update) and user-triggered refresh.

All our refreshes are done with MaterializedViewJobScheduler.
For periodic refresh, it must be automatically triggered by the system at present. We provide the registerScheduledJob interface to register a periodic refresh task, and the deregisterScheduledJob interface to deregister a periodic task. For other types of triggered refreshes, we provide addPendingJob and cancelJob interfaces to support, and periodic tasks are essentially called addPendingJob to add tasks for management.

<img width="651" alt="image" src="https://user-images.githubusercontent.com/4392280/163670022-d7b27044-7a4f-4ca2-ae82-0ec1c7059aa6.png">

Finally, it will be added to the pendingJob queue uniformly, and a dispatcher thread will perform a scheduling operation every 1s. This scheduling currently uses the minimum heap that comes with JDK, which can be replaced with a time wheel later, and can only be generated according to each MV. The logic of a running job is executed in the unrestricted refreshTaskPool, and a concurrency limit will be added to this operation later.

The same tasks that are automatically generated will also be merged here. For tasks manually generated by the user, we will not merge them.

It is also necessary to consider the logic of resuming the execution of some tasks after the FE restarts, and the logic of task cleaning. At present, this part of the logic has not been written, and will be added later. Comments are used in the code to mark where the log needs to be written.

2022-04-16 10:32 UTC, wanpengfei-git commented
#### [FE PR Coverage check]

:disappointed: **fail** : 241 / 336 (71.73%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewRefreshTask.java|0|18|00.00%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewPartitionRefreshTask.java|0|28|00.00%|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewSchedulerInfo.java|10|20|50.00%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewRefreshJob.java|56|71|78.87%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewJobManager.java|19|24|79.17%|
|:large_blue_circle:|com/starrocks/statistic/Constants.java|19|22|86.36%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewJobScheduler.java|108|122|88.52%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewRefreshJobBuilder.java|29|30|96.67%|

2022-04-18 14:00 UTC, wanpengfei-git commented
#### [FE PR Coverage check]

:disappointed: **fail** : 261 / 455 (57.36%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewRefreshTask.java|0|18|00.00%|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|0|22|00.00%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewPartitionRefreshTask.java|0|28|00.00%|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|9|00.00%|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewRefreshJobStatusChange.java|6|23|26.09%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewSchedulerInfo.java|11|26|42.31%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewJobScheduler.java|121|175|69.14%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewRefreshJob.java|56|76|73.68%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewJobManager.java|19|24|79.17%|
|:large_blue_circle:|com/starrocks/statistic/Constants.java|19|22|86.36%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewRefreshJobBuilder.java|29|30|96.67%|

2022-04-19 09:09 UTC, wanpengfei-git commented
#### [FE PR Coverage check]

:disappointed: **fail** : 309 / 492 (62.80%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|0|22|00.00%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewPartitionRefreshTask.java|0|19|00.00%|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|9|00.00%|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewRefreshJobStatusChange.java|6|23|26.09%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewRefreshTask.java|8|20|40.00%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewSchedulerInfo.java|11|26|42.31%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewJobScheduler.java|137|195|70.26%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewRefreshJob.java|72|91|79.12%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewJobManager.java|21|26|80.77%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewTaskException.java|5|6|83.33%|
|:large_blue_circle:|com/starrocks/statistic/Constants.java|20|23|86.96%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewRefreshJobBuilder.java|29|30|96.67%|

2022-04-19 12:49 UTC, Astralidea commented
run starrocks_fe_unittest

2022-04-19 12:50 UTC, Astralidea commented
run starrocks_fe_unittest

2022-04-19 13:05 UTC, wanpengfei-git commented
#### [FE PR Coverage check]

:disappointed: **fail** : 312 / 486 (64.20%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|0|22|00.00%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewPartitionRefreshTask.java|0|19|00.00%|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|9|00.00%|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewRefreshJobStatusChange.java|6|23|26.09%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewRefreshTask.java|8|20|40.00%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewSchedulerInfo.java|11|20|55.00%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewJobManager.java|138|196|70.41%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewJobExecutor.java|18|23|78.26%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewRefreshJob.java|77|94|81.91%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewTaskException.java|5|6|83.33%|
|:large_blue_circle:|com/starrocks/statistic/Constants.java|20|23|86.96%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewRefreshJobBuilder.java|29|30|96.67%|

2022-04-24 07:59 UTC, ABingHuang commented
there are some points that need to be consider:
1. should connect with create materialized view
2. should consider load image and read a Materialized view
3. should consider the concurrency control

2022-04-24 08:00 UTC, ABingHuang requested changes

2022-04-26 09:21 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/mv/MaterializedViewJobManager.java
> +                    LOG.warn("materialized view lock owner is null");
If a thread takes its own lock owner is null

2022-04-26 09:22 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/mv/MaterializedViewJobManager.java
> +        return lock.isHeldByCurrentThread();
If a thread holds its own lock, it will be here

2022-04-26 09:22 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/mv/MaterializedViewJobExecutor.java
> +            job.setStatus(Constants.MaterializedViewJobStatus.RETRYING);
Because you have to let the user know if he is running it for the first time or if he is trying again.

2022-04-26 09:24 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/mv/MaterializedViewJobManager.java
> +                Iterator<Long> pendingIterator = pendingJobMap.keySet().iterator();
This has been concurrency control through the above tryLock

2022-04-26 09:26 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/mv/MaterializedViewJobManager.java
> +        Queue<MaterializedViewRefreshJob> jobQueue = pendingJobMap.get(mvTableId);
This cannot use getOrDefault because if jobQueue is null it should be put a job in it. else it should merge the job.

2022-04-26 09:32 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/mv/MaterializedViewJobManager.java
> +        periodScheduledManager.put(info.getId(), info);
The replay operation is single-threaded and does not require concurrency control

2022-04-26 09:36 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/mv/MaterializedViewSchedulerInfo.java
> +    private Long id;
because catalog.nextId returns long

2022-04-26 09:36 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/mv/MaterializedViewRefreshJobBuilder.java
> +    @VisibleForTesting
The meaning of this Tag is that this method should be private, and now it is public just for testing.

2022-04-26 09:38 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/mv/MaterializedViewRefreshJob.java
> +    public void runTasks()  {
Because your refresh task is generated on demand when it is about to run. Instead of generating all tasks from the beginning.

2022-04-26 09:39 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/mv/MaterializedViewRefreshJob.java
> +                try {
This exception needs to be captured at the task granularity. It is possible that one of your tasks failed, but other tasks can be executed successfully.

2022-04-26 09:40 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/mv/MaterializedViewSchedulerInfo.java
> +    private MaterializedViewRefreshJobBuilder jobBuilder;
Because the user may submit a periodic Job, but the Job has not actually been created, this build is needed to create a specific Job.

2022-04-26 10:20 UTC, wanpengfei-git commented
#### [FE PR Coverage check]

:disappointed: **fail** : 314 / 486 (64.61%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|0|22|00.00%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewPartitionRefreshTask.java|0|19|00.00%|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|9|00.00%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewRefreshJobStatusChange.java|6|23|26.09%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewRefreshTask.java|8|20|40.00%|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|1|2|50.00%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewSchedulerInfo.java|11|20|55.00%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewJobManager.java|139|198|70.20%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewJobExecutor.java|18|23|78.26%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewRefreshJob.java|77|94|81.91%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewTaskException.java|5|6|83.33%|
|:large_blue_circle:|com/starrocks/mv/MaterializedViewRefreshJobBuilder.java|29|30|96.67%|
|:large_blue_circle:|com/starrocks/statistic/Constants.java|20|20|100.00%|

2022-04-26 12:12 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/mv/MaterializedViewJobExecutor.java
> +                job.runTasks();
Exception is including InterruptedException

2022-04-26 12:15 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/mv/MaterializedViewRefreshJob.java
> +    public void runTasks()  {
Exception is including InterruptedException

2022-04-26 12:23 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/mv/MaterializedViewJobManager.java
> +    Deque<MaterializedViewRefreshJob> jobHistory;
If encapsulated as an interface, there will be many methods in this interface.

2022-04-26 12:26 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/mv/MaterializedViewJobManager.java
> +        Iterator<MaterializedViewRefreshJob> jobIter = jobHistory.iterator();
this JobHistory is Deque. if use map we will manage sort by time?

2022-04-26 12:41 UTC, Astralidea commented on fe/fe-core/src/main/java/com/starrocks/mv/MaterializedViewJobManager.java
> +        dispatchTaskScheduler.scheduleAtFixedRate(() -> {
you are right!

2022-04-26 13:26 UTC, closed without merging

2022-04-27 02:33 UTC, Astralidea commented
This close because commit issue, new discussion will in #5558