[Enhancement] add partition scan infomation in audit log
StarRocks/starrocks pull request #51853
Opened 2024-10-13 03:42 UTC by MatthewH00

## Why I'm doing:
  When user set a long TTL for table partitions, but the historic partitions are never visited or rarely visited, it would cause unnecessary storage waste and metadata pressure. 
  So more detailed partition visit audit information is needed to distinguish cold and hot partitions, so as to better data governance. 
  With the help of external tools, it is easy to parse the source table from query SQL, but it is difficult to parse the visit partition information.

## What I'm doing:
Add a new FE session variable `enable_scan_partitions_audit` to control turn on or not, the fe.audit.log file would add a new item ScanPartitions after ScanRows like:

`ScanPartitions="[{catalogName:default_catalog,databaseName:db1,tableName:tab1,partitionIds:[p20241001, p20241002]}, {catalogName:default_catalog,databaseName:db2,tableName:tab2,partitionIds:[tab2]}]"
`
explain as follows:

```
- catalogName: only support internal catalog now

- databaseName: database name

- tableName: table name

- partitionIds: when is partitioned table display visit partitionId, when is unpartitioned table display table name

```
Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [y] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [y] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [y] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [y] I have checked the version labels which the pr will be auto-backported to the target branch
  - [y] 3.3
  - [y] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

2024-10-18 08:51 UTC, MatthewH00 commented
@kevincai Hi Could you please help to review the pr when you have free time ?

2024-10-18 08:59 UTC, kevincai commented
> @kevincai Hi Could you please help to review the pr when you have free time ?

I may not be adequate to  review this PR. But I am kind of objection to add scanPartitions into audit log, (not the query dump), it can be easily blow the audit log by a single full table scanning of thousands of partitions.

2024-10-18 09:10 UTC, MatthewH00 commented
> > @kevincai Hi Could you please help to review the pr when you have free time ?
> 
> I may not be adequate to review this PR. But I am kind of objection to add scanPartitions into audit log, (the query dump might be fine), it can be easily blow the audit log by a single full table scanning of thousands of partitions.

From the view of a cluster administrator, the partitions scan info is needed when faced the Insufficient storage or metadata pressure(tablet too many)，it would become a reference to data governance. And consider the metadata pressure , it would not create the table with too many partition . From the 3.3.2 , it looks provide a param `max_partition_num_per_table` 
 to limit the partition number of table

2024-10-18 09:19 UTC, kevincai commented
> > > @kevincai Hi Could you please help to review the pr when you have free time ?
> > 
> > 
> > I may not be adequate to review this PR. But I am kind of objection to add scanPartitions into audit log, (the query dump might be fine), it can be easily blow the audit log by a single full table scanning of thousands of partitions.
> 
> From the view of a cluster administrator, the partitions scan info is needed when faced the Insufficient storage or metadata pressure(tablet too many)，it would become a reference to data governance. And consider the metadata pressure , it would not create the table with too many partition . From the 3.3.2 , it looks provide a param `max_partition_num_per_table` to limit the partition number of table

There are alternative solutions, may not necessary to get it through audit log. e.g. through '/statistics' interface and thrilling down to db-table-partition level. If it is not there, it is good to enhance it.

2024-10-18 10:14 UTC, MatthewH00 commented
> > > > @kevincai Hi Could you please help to review the pr when you have free time ?
> > > 
> > > 
> > > I may not be adequate to review this PR. But I am kind of objection to add scanPartitions into audit log, (the query dump might be fine), it can be easily blow the audit log by a single full table scanning of thousands of partitions.
> > 
> > 
> > From the view of a cluster administrator, the partitions scan info is needed when faced the Insufficient storage or metadata pressure(tablet too many)，it would become a reference to data governance. And consider the metadata pressure , it would not create the table with too many partition . From the 3.3.2 , it looks provide a param `max_partition_num_per_table` to limit the partition number of table
> 
> There are alternative solutions, may not necessary to get it through audit log. e.g. through '/statistics' interface and thrilling down to db-table-partition level. If it is not there, it is good to enhance it.

For detailed data governance, may be it is good for partitions scan info in the level of single sql. To avoid to make the audit log file too large , add a new FE variable to limit the number of the printed scan partitions , exceed the limit would display like `partitionIds:[p20241001,...,p20241030]}` it would be ok?

2024-10-22 01:41 UTC, MatthewH00 commented
> > For detailed data governance, may be it is good for partitions scan info in the level of single sql. To avoid to make the audit log file too large , add a new FE variable to limit the number of the printed scan partitions , exceed the limit would display like `partitionIds:[p20241001,...,p20241030]}` it would be ok?
> 
> Would be good to have others thought on this PR, not just mine.
Could you please help to look for a related RD classmate to review the PR? I submit the PR last week Monday but looks nobody to review it

2024-10-22 01:43 UTC, MatthewH00 commented
> > For detailed data governance, may be it is good for partitions scan info in the level of single sql. To avoid to make the audit log file too large , add a new FE variable to limit the number of the printed scan partitions , exceed the limit would display like `partitionIds:[p20241001,...,p20241030]}` it would be ok?
> 
> Would be good to have others thought on this PR, not just mine.

Could you please help to look for a related RD classmate to review the PR? I submit the PR last week Monday but looks nobody to review it

2024-11-15 01:34 UTC, MatthewH00 commented
@trueeyu Hi Could you please help review the PR? I submit the PR last month ,but looks nobody to review it.

2024-11-29 01:47 UTC, MatthewH00 commented
@Seaven Hi Could you please help review this pr when have free time? 
The PR achieve add partition scan infomation in audit log. From the view of cluster administrator,  the partitions scan infomation is needed when faced the Insufficient storage or metadata pressure(too many tablet)，it would become a reference to data governance.

2024-12-02 11:36 UTC, murphyatwork requested changes
AuditLog literally means it's used to audit the query in the system, but not used to inspect the performance.

I would suggest create a view in `information_schema` to track the data accessing information, it's much more easy to use.

2024-12-03 07:26 UTC, MatthewH00 commented
> > AuditLog literally means it's used to audit the query in the system, but not used to inspect the performance.
> > I would suggest create a view in `information_schema` to track the data accessing information, it's much more easy to use.
> 
> 1.It is not used to inspect the performance, the partition scan info like ScanRows/ScanBytes only display more detailed information of a query. 2.for detailed data governance, may be it is good for partitions scan info in the level of single sql, would provide user with more choices by analyze fe.audit.log, like: 1)optimize/governance the query of scan too many partitons 2)audit different time ranges/account for different cluster/business's actual situation 3)distinguish cold and hot partitions , drop never visited or rarely visited historic partition to reduce unnecessary storage waste and metadata pressure ... 3.the pr currently only aimed to internal table, when query exteral table like hive/paimon，the data governance of hive/paimon also need partition scan infomation. like Trino it also provide the partion scan infomation. I would extend exteral table like hive/paimon partition scan info later. 4.later i would place the new added item scanPartitions mapping to audit log table by AuditLoader plugin , It is also easy to use compared to view in information_schema.
> 
> In summary, i think print the the partition scan into fe.audit.log would more flexible than view in information_schema.

@murphyatwork Do you agree with the viewpoint I mentioned above? 
Like Trino, it also display the partition scan info at the single query level, would provide user with more choices for hive/paimon table's data governance by analyze audit log.
the pr currently only aimed to starrocks internal table, for external table like hive/paimon partition scan audit infomation, I would extend later.

2024-12-03 10:21 UTC, MatthewH00 commented
@murphyatwork add a trino query audit log sample like this, it print the partition scan info into audit log at the single query level:
![trinoQueryAuditLogSamplePic](https://github.com/user-attachments/assets/d8357ca2-dd49-4b19-a4d9-0a1a09153f8c)

2024-12-05 01:56 UTC, MatthewH00 commented
> > AuditLog literally means it's used to audit the query in the system, but not used to inspect the performance.
> > I would suggest create a view in `information_schema` to track the data accessing information, it's much more easy to use.
> 
> 1.It is not used to inspect the performance, the partition scan info like ScanRows/ScanBytes only display more detailed information of a query. 2.for detailed data governance, may be it is good for partitions scan info in the level of single sql, would provide user with more choices by analyze fe.audit.log, like: 1)optimize/governance the query of scan too many partitons 2)audit different time ranges/account for different cluster/business's actual situation 3)distinguish cold and hot partitions , drop never visited or rarely visited historic partition to reduce unnecessary storage waste and metadata pressure ... 3.the pr currently only aimed to internal table, when query exteral table like hive/paimon，the data governance of hive/paimon also need partition scan infomation. like Trino it also provide the partion scan infomation. I would extend exteral table like hive/paimon partition scan info later. 4.later i would place the new added item scanPartitions mapping to audit log table by AuditLoader plugin , It is also easy to use compared to view in information_schema.
> 
> In summary, i think print the the partition scan into fe.audit.log would more flexible than view in information_schema.

@murphyatwork For create a view in `information_schema` to track the data accessing information , i have several question:
1)view is not real store data, for data governance usually need trace back to the last 30/90/180/365 days, too many partition scan data would not cause the fe resource waste seriously?
2)when use starrocks query external table like hive/paimon, the partition scan data is also suitable to query by a view in `information_schema`?? Because hive/paimon table also need data governance accoding to the partition scan infomation.

So based the the viewpoint I mentioned above, i think may be good for partitions scan info in the level of single sql by print into fe.audit.log. Please consider it.
(add a trino query audit log sample like this, it print the partition scan info into audit log at the single query level:
![trinoQueryAuditLogSamplePic](https://github.com/user-attachments/assets/c59bce87-db10-49fe-8cbb-2ab7f2aaaff3)
)

2025-06-01 21:12 UTC, closed without merging