[Enhancement] Add connection id information to audit event(#53667)
StarRocks/starrocks pull request #53668
Opened 2024-12-06 07:25 UTC by immutablecodes

## Why I'm doing:

Make it easy to trace the query's corresponding connection.

## What I'm doing:

Add connection id information to audit event.

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [x] 3.3
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0

2024-12-17 10:54 UTC, murphyatwork requested changes
But how do you get the connectionId after the query? how to use it to diagnose issues? 
I don't think you really need it

2024-12-19 11:23 UTC, immutablecodes commented
> But how do you get the connectionId after the query? how to use it to diagnose issues? I don't think you really need it

Hi @murphyatwork , we can get connectionId from here: https://github.com/StarRocks/starrocks/blob/3.3.7/fe/fe-core/src/main/java/com/starrocks/mysql/nio/AcceptListener.java#L83, after this patch I can statistic how many queries requested from the same connection.

2024-12-20 06:56 UTC, murphyatwork commented
> > But how do you get the connectionId after the query? how to use it to diagnose issues? I don't think you really need it
> 
> Hi @murphyatwork , we can get connectionId from here: https://github.com/StarRocks/starrocks/blob/3.3.7/fe/fe-core/src/main/java/com/starrocks/mysql/nio/AcceptListener.java#L83, after this patch I can statistic how many queries requested from the same connection.

that's an interesting solution. 

but back to your question, "how many queries requested from the same connection" , may i ask why do you need this kind of detailed information? for performance optimization purpose, or just for debugging ?

2024-12-20 07:50 UTC, immutablecodes commented
> > > But how do you get the connectionId after the query? how to use it to diagnose issues? I don't think you really need it
> > 
> > 
> > Hi @murphyatwork , we can get connectionId from here: https://github.com/StarRocks/starrocks/blob/3.3.7/fe/fe-core/src/main/java/com/starrocks/mysql/nio/AcceptListener.java#L83, after this patch I can statistic how many queries requested from the same connection.
> 
> that's an interesting solution.
> 
> but back to your question, "how many queries requested from the same connection" , may i ask why do you need this kind of detailed information? for performance optimization purpose, or just for debugging ?

mainly for debugging purpose, or to be more precisely for monitoring purpose.

2024-12-24 05:13 UTC, murphyatwork commented
> > > > But how do you get the connectionId after the query? how to use it to diagnose issues? I don't think you really need it
> > > 
> > > 
> > > Hi @murphyatwork , we can get connectionId from here: https://github.com/StarRocks/starrocks/blob/3.3.7/fe/fe-core/src/main/java/com/starrocks/mysql/nio/AcceptListener.java#L83, after this patch I can statistic how many queries requested from the same connection.
> > 
> > 
> > that's an interesting solution.
> > but back to your question, "how many queries requested from the same connection" , may i ask why do you need this kind of detailed information? for performance optimization purpose, or just for debugging ?
> 
> mainly for debugging purpose, or to be more precisely for monitoring purpose.

If it's only for temporary debug purpose, i don't recommend introduce this function into the production codebase.
If you want to monitor the number of queries from different client, i would suggest use this function https://github.com/StarRocks/starrocks/issues/47699, putting a custom_query_id in the context then count it from the auditlog

2025-05-20 13:59 UTC, dolfinus commented
@murphyatwork adding connectionId to audit log may be beneficial for some users. For example, this allows to link queries executed by the same user as a part of some specific application (#58963), without introducing `custom_query_id` for each executed query in StarRocks.
Also, `custom_query_id` have to be unique, which leads to complicated solutions, e.g. adding a prefix for all queries generated by specific application, and so on.

2025-06-09 12:20 UTC, dolfinus commented
Alternative implementations:
* Count number of queries executed within same sessionId (#59569)
* Pass `customSessionName` which is like `customQueryId` but doesn't reset after query is finished (#59754)

2026-02-02 02:16 UTC, closed without merging