[Doc] add query feedback doc
StarRocks/starrocks pull request #53785
Opened 2024-12-10 12:24 UTC by stephen-shelby

## Why I'm doing:

## What I'm doing:

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.4
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0

2025-01-07 18:42 UTC, DanRoscigno requested changes

2025-01-07 18:42 UTC, DanRoscigno commented on docs/en/using_starrocks/query_feedback.md
> +- A tuning guide can only be used to the exact same query based on which it was generated. It is not applicable to queries with the same pattern but different parameters.
```suggestion
- A tuning guide can only be used for the exact same query for which it was generated. It is not applicable to queries with the same pattern but different parameters.
```

2025-01-08 00:21 UTC, EsoragotoSpirit approved these changes

2025-01-10 07:48 UTC, andyziye approved these changes

2025-01-10 07:50 UTC, merged

2025-01-10 07:57 UTC, EsoragotoSpirit commented
@mergify backport branch-3.4