[WIP][Feature] Adapt to catalog in fe
StarRocks/starrocks pull request #6508
Opened 2022-05-25 06:49 UTC by stephen-shelby

## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

2022-05-25 07:43 UTC, stephen-shelby commented
run starrocks_fe_unittest

2022-05-25 07:49 UTC, stephen-shelby commented
run starrocks_fe_unittest

2022-05-25 07:51 UTC, stephen-shelby commented
run starrocks_fe_unittest

2022-05-25 07:51 UTC, caneGuy commented
run starrocks_fe_unittest

2022-05-25 08:09 UTC, stephen-shelby commented
cc @HangyuanLiu

2022-05-25 08:13 UTC, RowenWoo requested changes

2022-05-25 08:13 UTC, RowenWoo commented on fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaCache.java
> +        if (db == null || db.getName() == null) {
```suggestion
        if (db == null && db.getName() == null) {
```

2022-05-25 08:52 UTC, stephen-shelby commented
run starrocks_fe_unittest

2022-05-25 11:31 UTC, DorianZheng commented on fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
> +        List<String> parts = qualifiedName.getParts();
nit: plz add some comments

2022-05-25 11:38 UTC, DorianZheng commented on fe/fe-core/src/main/java/com/starrocks/sql/common/MetaUtils.java
> +            if (CatalogMgr.isInternalCatalog(tableName.getCatalog())) {
nit: extract a function, this statement is used everywhere

2022-05-25 15:08 UTC, DorianZheng commented on fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMgr.java
> +    private final ReadWriteLock connectorLock = new ReentrantReadWriteLock();
nit: use db_lock instead?

2022-05-25 15:45 UTC, stephen-shelby commented on fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
> +        List<String> parts = qualifiedName.getParts();
done

2022-05-25 16:47 UTC, stephen-shelby commented
run starrocks_fe_unittest

2022-05-25 18:08 UTC, wanpengfei-git commented
#### [FE PR Coverage check]

:heart_eyes: **pass** : 120 / 133 (90.23%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|2|3|66.67%|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|21|26|80.77%|
|:large_blue_circle:|com/starrocks/sql/common/MetaUtils.java|5|6|83.33%|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|6|7|85.71%|
|:large_blue_circle:|com/starrocks/connector/ConnectorMgr.java|24|27|88.89%|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|9|10|90.00%|
|:large_blue_circle:|com/starrocks/analysis/TableName.java|16|17|94.12%|
|:large_blue_circle:|com/starrocks/server/MetadataMgr.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/server/CatalogMgr.java|28|28|100.00%|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaCache.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowStmtAnalyzer.java|5|5|100.00%|
|:large_blue_circle:|com/starrocks/analysis/Analyzer.java|1|1|100.00%|

2022-05-26 07:47 UTC, DorianZheng approved these changes
LGTM

2022-05-26 08:01 UTC, caneGuy approved these changes

2022-05-26 13:55 UTC, HangyuanLiu approved these changes

2022-05-26 13:55 UTC, merged