[MaterializedView] forbid direct ingest to MaterializedView [P2] #4795
StarRocks/starrocks pull request #7004
Opened 2022-06-08 09:59 UTC by zddr

## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #4795 

## Problem Summary(Required) ：

2022-06-09 06:45 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java
> +        if (table instanceof MaterializedView) {
add a strategy to let the task refresh framework pass this check.

2022-06-09 09:43 UTC, zddr commented
run starrocks_fe_unittest

2022-06-09 09:48 UTC, wanpengfei-git commented
#### [FE PR Coverage check]

:disappointed: **fail** : 11 / 14 (78.57%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|1|2|50.00%|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadJob.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/analysis/InsertStmt.java|4|4|100.00%|
|:large_blue_circle:|com/starrocks/load/BrokerFileGroup.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/load/DeleteHandler.java|2|2|100.00%|

2022-06-09 09:57 UTC, Astralidea submitted a review, later dismissed

2022-06-09 11:47 UTC, HangyuanLiu requested changes
1. The error message should be more clear. "not support MaterializedView" is obviously not an error message that users can clearly understand.
2. Delete and Update should be checked like Insert, in DeleteAnalyzer and UpdateAnalyzer respectively.
3. The verification of load-related statements should also be checked in the Analyzer stage

2022-06-14 02:44 UTC, kangkaisen commented
run starrocks_fe_unittest

2022-06-14 02:46 UTC, ABingHuang submitted a review, later dismissed
LGTM

2022-06-14 02:47 UTC, HangyuanLiu submitted a review, later dismissed

2022-06-14 02:49 UTC, Astralidea approved these changes, later dismissed

2022-06-14 03:01 UTC, ABingHuang commented
run starrocks_fe_unittest

2022-06-14 07:01 UTC, wanpengfei-git commented
#### [FE PR Coverage check]

:heart_eyes: **pass** : 20 / 23 (86.96%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|3|00.00%|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadJob.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/analysis/InsertStmt.java|4|4|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/analysis/DataDescription.java|5|5|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/DeleteAnalyzer.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/UpdateAnalyzer.java|3|3|100.00%|

2022-06-14 07:25 UTC, Astralidea approved these changes

2022-06-14 12:49 UTC, ABingHuang approved these changes, later dismissed
LGTM

2022-06-14 12:50 UTC, Astralidea submitted a review, later dismissed

2022-06-15 06:17 UTC, zddr commented
run starrocks_fe_unittest

2022-06-15 06:45 UTC, zddr commented
run starrocks_fe_unittest

2022-06-15 06:57 UTC, wanpengfei-git commented
#### [FE PR Coverage check]

:disappointed: **fail** : 20 / 26 (76.92%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|3|00.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|3|6|50.00%|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadJob.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/analysis/InsertStmt.java|4|4|100.00%|
|:large_blue_circle:|com/starrocks/analysis/DataDescription.java|5|5|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/DeleteAnalyzer.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/UpdateAnalyzer.java|3|3|100.00%|

2022-06-15 07:42 UTC, kangkaisen approved these changes

2022-06-16 01:35 UTC, HangyuanLiu approved these changes

2022-06-16 06:24 UTC, merged