[MaterializedView] Generate MaterializedView Full DDL SQL for ShowCreateTableStmt and ShowMaterializedViewStatement
StarRocks/starrocks pull request #8398
Opened 2022-07-07 11:44 UTC by Crystal-LiuJing

## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #8396

## Problem Summary(Required) ：

1 show full ddl_sql for new MaterializedView

2022-07-07 13:51 UTC, Crystal-LiuJing commented
> There are a lot of UTs that may need to be fixed.



> There are a lot of UTs that may need t

2022-07-07 13:58 UTC, Crystal-LiuJing commented
> There are a lot of UTs that may need to be fixed.

yes , i'll check it

2022-07-08 08:11 UTC, HangyuanLiu commented
toSql is an obsolete interface and cannot be used in actual functional code. Relevant code can be moved into AST2SQL

2022-07-10 15:22 UTC, wanpengfei-git commented
#### [FE PR Coverage check]

:heart_eyes: **pass** : 57 / 65 (87.69%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|4|00.00%|
|:large_blue_circle:|com/starrocks/catalog/ExpressionRangePartitionInfo.java|20|23|86.96%|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|37|38|97.37%|

2022-07-10 15:37 UTC, wanpengfei-git commented
#### [FE PR Coverage check]

:heart_eyes: **pass** : 55 / 62 (88.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|4|00.00%|
|:large_blue_circle:|com/starrocks/catalog/ExpressionRangePartitionInfo.java|20|23|86.96%|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|35|35|100.00%|

2022-07-12 01:45 UTC, Astralidea commented
run starrocks_fe_unittest

2022-07-12 03:16 UTC, Astralidea commented
run starrocks_fe_unittest

2022-07-12 06:04 UTC, Astralidea commented
run starrocks_fe_unittest

2022-07-12 06:40 UTC, Astralidea commented
run starrocks_fe_unittest

2022-07-12 07:05 UTC, ABingHuang requested changes

2022-07-12 07:05 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java
> +                if (asyncRefreshContext.getTimeUnit() != null) {
should consider the situation of 
REFRESH ASYNC without interval.

2022-07-12 14:13 UTC, Crystal-LiuJing commented
run starrocks_fe_unittest

2022-07-13 06:55 UTC, Astralidea approved these changes

2022-07-13 10:06 UTC, ABingHuang approved these changes
LGTM

2022-07-13 10:07 UTC, wanpengfei-git commented
run starrocks_admit_test

2022-07-13 11:58 UTC, chaoyli approved these changes

2022-07-13 11:59 UTC, merged