Enhancement: share TabletSchema to reduce memory usage
StarRocks/starrocks pull request #846
Opened 2021-10-23 08:48 UTC by sduzh

Close issue #807

A 64 bits integer field named `id` is added in `TabletSchemaPB` ,with its
value assigned by the master FE node, and the following properties
are ensured by the master FE:
- all tablets from the same table or materialized view will have the same `id`
- tablets from different tables or materialized views will have different `id`.

On each BE node, a global hash map was created to map from the `id` to
`std::shared_ptr<TabletSchema>`. When creating a new tablet or loading
already exists tablets from disk after the restart, the `id` will be checked
and only one `TabletSchema` will be created for all tablets with the same
 `id`.

Please note that this patch only works for newly-created tablets. For those
already-created tablets, their `TabletShema`s will not be shared among each other.

2021-10-23 12:48 UTC, chaoyli requested changes

2021-10-25 04:48 UTC, gengjun-git reviewed
fe meta change approved

2021-10-25 06:21 UTC, chaoyli requested changes

2021-10-25 06:50 UTC, chaoyli approved these changes

2021-10-25 07:26 UTC, gengjun-git approved these changes

2021-10-25 07:28 UTC, merged