[Feature] Support select xxx into outfile without broker
StarRocks/starrocks pull request #9201
Opened 2022-07-26 03:13 UTC by xiaoyong-z

## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9200

## Problem Summary(Required) ：

Support select xxx into outfile without broker

2022-07-27 13:21 UTC, chaoyli commented on be/src/fs/fs.cpp
> +StatusOr<std::unique_ptr<FileSystem>> FileSystem::CreateUniqueFromString(std::string_view uri, FSOptions options) {
const FSOptions&

2022-07-27 13:21 UTC, chaoyli commented on be/src/fs/fs.cpp
> +StatusOr<std::shared_ptr<FileSystem>> FileSystem::CreateSharedFromString(std::string_view uri, FSOptions options) {
const FSOptions&

2022-07-27 13:21 UTC, chaoyli commented on be/src/fs/fs_hdfs.cpp
> +    if (handle.type != HdfsFsHandle::Type::HDFS) {
add path in the error status

2022-08-02 13:18 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 8 / 23 (34.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/ResultSink.java|0|1|00.00%|[87]|
|:large_blue_circle:|com/starrocks/analysis/OutFileClause.java|8|22|36.36%|[165, 166, 188, 224, 225, 226, 227, 229, 230, 231, 232, 233, 234, 235]|

2022-08-02 15:25 UTC, xiaoyong-z commented
run starrocks_be_build

2022-08-02 15:25 UTC, xiaoyong-z commented
run starrocks_be_unittest

2022-08-02 15:25 UTC, xiaoyong-z commented
run starrocks_clang-format

2022-08-02 15:25 UTC, xiaoyong-z commented
run starrocks_clang-tidy

2022-08-02 15:25 UTC, xiaoyong-z commented
run starrocks_tscancode

2022-08-02 15:26 UTC, xiaoyong-z commented
run starrocks_fe_unittest

2022-08-03 02:17 UTC, xiaoyong-z commented
run starrocks_be_unittest

2022-08-03 02:17 UTC, xiaoyong-z commented
run starrocks_fe_unittest

2022-08-03 02:33 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 8 / 23 (34.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/ResultSink.java|0|1|00.00%|[87]|
|:large_blue_circle:|com/starrocks/analysis/OutFileClause.java|8|22|36.36%|[165, 166, 188, 224, 225, 226, 227, 229, 230, 231, 232, 233, 234, 235]|

2022-08-03 03:28 UTC, chaoyli submitted a review, later dismissed

2022-08-03 03:39 UTC, meegoo requested changes

2022-08-03 03:39 UTC, meegoo commented on fe/fe-core/src/main/java/com/starrocks/analysis/OutFileClause.java
> +        if (!outfile_without_broker) {
outfile_without_broker always false?

2022-08-03 05:11 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 8 / 24 (33.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/ResultSink.java|0|1|00.00%|[87]|
|:large_blue_circle:|com/starrocks/analysis/OutFileClause.java|8|23|34.78%|[165, 166, 168, 189, 225, 226, 227, 228, 230, 231, 232, 233, 234, 235, 236]|

2022-08-03 06:30 UTC, chaoyli approved these changes

2022-08-03 06:33 UTC, meegoo approved these changes

2022-08-03 11:49 UTC, xiaoyong-z commented
run starrocks_admit_test

2022-08-03 13:03 UTC, Astralidea approved these changes

2022-08-03 13:04 UTC, merged

2022-08-03 13:04 UTC, wanpengfei-git commented
run starrocks_admit_test

2022-08-03 13:17 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 8 / 24 (33.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/ResultSink.java|0|1|00.00%|[87]|
|:large_blue_circle:|com/starrocks/analysis/OutFileClause.java|8|23|34.78%|[165, 166, 168, 189, 225, 226, 227, 228, 230, 231, 232, 233, 234, 235, 236]|

2022-08-03 13:24 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 8 / 24 (33.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/ResultSink.java|0|1|00.00%|[87]|
|:large_blue_circle:|com/starrocks/analysis/OutFileClause.java|8|23|34.78%|[165, 166, 168, 189, 225, 226, 227, 228, 230, 231, 232, 233, 234, 235, 236]|

2022-08-03 13:32 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 8 / 24 (33.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/ResultSink.java|0|1|00.00%|[87]|
|:large_blue_circle:|com/starrocks/analysis/OutFileClause.java|8|23|34.78%|[165, 166, 168, 189, 225, 226, 227, 228, 230, 231, 232, 233, 234, 235, 236]|

2022-08-03 13:44 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 8 / 24 (33.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/ResultSink.java|0|1|00.00%|[87]|
|:large_blue_circle:|com/starrocks/analysis/OutFileClause.java|8|23|34.78%|[165, 166, 168, 189, 225, 226, 227, 228, 230, 231, 232, 233, 234, 235, 236]|

2022-08-03 13:55 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 8 / 24 (33.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/ResultSink.java|0|1|00.00%|[87]|
|:large_blue_circle:|com/starrocks/analysis/OutFileClause.java|8|23|34.78%|[165, 166, 168, 189, 225, 226, 227, 228, 230, 231, 232, 233, 234, 235, 236]|

2022-08-03 14:13 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:disappointed: **fail** : 8 / 24 (33.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/ResultSink.java|0|1|00.00%|[87]|
|:large_blue_circle:|com/starrocks/analysis/OutFileClause.java|8|23|34.78%|[165, 166, 168, 189, 225, 226, 227, 228, 230, 231, 232, 233, 234, 235, 236]|