add missing parameters in stop_be.sh
StarRocks/starrocks pull request #9428
Opened 2022-08-01 09:38 UTC by yongbingwang

2022-08-01 10:43 UTC, imay approved these changes

2022-08-01 12:14 UTC, choury commented
"Graceful exit"  feature haven't  been backported to 2.3, we should not add this.

2022-08-01 12:54 UTC, imay requested changes
sorry, gracefully exit not in 2.3

2022-08-02 03:17 UTC, wanpengfei-git approved these changes

2022-08-02 03:48 UTC, merged