restrict create or alter mv,UnitIdentifier only support second,minute…
StarRocks/starrocks pull request #9465
Opened 2022-08-02 06:54 UTC by zddr

…,hour or day.

## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes # 9446

## Problem Summary(Required) ：

2022-08-02 07:42 UTC, zddr commented
run starrocks_fe_unittest

2022-08-02 08:11 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 14 / 16 (87.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|14|16|87.50%|[1035, 1117]|

2022-08-02 12:31 UTC, Astralidea submitted a review, later dismissed

2022-08-02 12:32 UTC, Astralidea commented
run starrocks_admit_test

2022-08-03 03:19 UTC, ABingHuang requested changes

2022-08-03 03:19 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
> +                if (!("SECOND".equalsIgnoreCase(description) || "MINUTE".equalsIgnoreCase(description) ||
extract this logic into a function and call it in both create and alter.
And more, push supported units into a unmodifiable set and just use find to judge whether the unit is supported.
And more, add an UT for this change.

2022-08-03 06:56 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 16 / 18 (88.89%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|16|18|88.89%|[1008, 1128]|

2022-08-03 06:59 UTC, Astralidea submitted a review, later dismissed

2022-08-03 07:12 UTC, ABingHuang requested changes
add an UT for alter materialized view

2022-08-03 07:12 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java
> +        if (refreshSchemeDesc instanceof AsyncRefreshSchemeDesc) {
add an UT for alter materialized view

2022-08-03 08:19 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 17 / 18 (94.44%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|17|18|94.44%|[1008]|

2022-08-03 09:16 UTC, Astralidea commented
run starrocks_admit_test

2022-08-03 09:16 UTC, Astralidea approved these changes
LGTM

2022-08-03 09:19 UTC, ABingHuang approved these changes
LGTM

2022-08-03 09:19 UTC, wanpengfei-git commented
run starrocks_admit_test

2022-08-03 11:47 UTC, chaoyli approved these changes

2022-08-03 11:48 UTC, merged