[Bugfixi] not support create mv by mv #9543
StarRocks/starrocks pull request #9576
Opened 2022-08-04 09:56 UTC by QingdongZeng3

[Bugfix] not support create mv by mv #9543

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9543 

## Problem Summary(Required) ：

```
CREATE TABLE t1
(a BIGINT,
b BIGINT,
c BIGINT,
d BIGINT,
e BIGINT,
f BIGINT)
DUPLICATE KEY(a)
DISTRIBUTED BY HASH(a) BUCKETS 10
PROPERTIES ("replication_num" = "1");

CREATE MATERIALIZED VIEW mv1
DISTRIBUTED BY HASH(a) BUCKETS 10
REFRESH ASYNC
AS SELECT a, b, c
FROM t1;

CREATE MATERIALIZED VIEW mv2
DISTRIBUTED BY HASH(a) BUCKETS 10
REFRESH ASYNC
AS SELECT a, b, c
FROM mv1;
```

Result:
```
MySQL [n1]> CREATE MATERIALIZED VIEW mv2
    -> DISTRIBUTED BY HASH(a) BUCKETS 10
    -> REFRESH ASYNC
    -> AS SELECT a, b, c
    -> FROM mv1;
ERROR 1064 (HY000): Materialized view not supports base on Materialized view so far, but the type of table: mv1 is: MATERIALIZED_VIEW
```

![image](https://user-images.githubusercontent.com/70745826/182819439-d2def87e-b710-48d8-af51-645db0fa1c12.png)

2022-08-04 09:57 UTC, QingdongZeng3 commented
@Astralidea PTAL

2022-08-04 10:06 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|3|3|100.00%|[]|

2022-08-04 10:31 UTC, Astralidea approved these changes, later dismissed

2022-08-04 11:11 UTC, QingdongZeng3 commented
run starrocks_admit_test

2022-08-04 11:15 UTC, ABingHuang requested changes

2022-08-04 11:15 UTC, ABingHuang commented on fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java
> +                            "Materialized view not supports base on Materialized view so far, but the type of table: " +
creating a materialized view from materialized view is not supported now. The type of table: + table.getName is a materialized view.

2022-08-05 03:01 UTC, QingdongZeng3 commented
run starrocks_fe_unittest

2022-08-05 03:20 UTC, QingdongZeng3 commented
run starrocks_fe_unittest

2022-08-05 04:28 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|3|3|100.00%|[]|

2022-08-05 04:36 UTC, Astralidea approved these changes

2022-08-05 04:38 UTC, imay commented
@QingdongZeng3 should merged into branch-2.4
@mergify cherry-pick branch-2.4

2022-08-05 04:59 UTC, ABingHuang approved these changes
LGTM

2022-08-05 05:00 UTC, wanpengfei-git commented
run starrocks_admit_test

2022-08-05 06:09 UTC, gengjun-git approved these changes

2022-08-05 06:09 UTC, merged

2022-08-05 06:11 UTC, Astralidea commented
@Mergifyio backport branch-2.4

2022-08-05 06:34 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|3|3|100.00%|[]|

2022-08-05 06:56 UTC, wanpengfei-git commented
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|3|3|100.00%|[]|